### ISSUE TITLE
SDL_GFX and SDL_Image builds fail

### ISSUE THREAD

**Issue by mrfixit2001** [libsdl-org/sdl12-compat#103]
Trying to replace sdl1.2 in my build system with sdl12-compat, and when building sdl_gfx it fails. Note that I am not using X11 at all.

SDL_gfxPrimitives.c: In function 'characterColor':
SDL_gfxPrimitives.c:5933:41: error: 'SDL_HWSURFACE' undeclared (first use in this function); did you mean 'SDL_SWSURFACE'?
 5933 |    SDL_CreateRGBSurface(SDL_SWSURFACE | SDL_HWSURFACE | SDL_SRCALPHA,
      |                                         ^~~~~~~~~~~~~
      |                                         SDL_SWSURFACE
SDL_gfxPrimitives.c:5933:41: note: each undeclared identifier is reported only once for each function it appears in
SDL_gfxPrimitives.c:5933:57: error: 'SDL_SRCALPHA' undeclared (first use in this function)
 5933 |    SDL_CreateRGBSurface(SDL_SWSURFACE | SDL_HWSURFACE | SDL_SRCALPHA,
      |                                                         ^~~~~~~~~~~~
SDL_gfxPrimitives.c:5957:3: warning: implicit declaration of function 'SDL_SetAlpha'; did you mean 'SDL_metal_h_'? [-Wimplicit-function-declaration]
 5957 |   SDL_SetAlpha(gfxPrimitivesFont[ci], SDL_SRCALPHA, 255);
      |   ^~~~~~~~~~~~
      |   SDL_metal_h_
libtool: compile:  /home/output/host/bin/arm-buildroot-linux-gnueabihf-gcc -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"SDL_gfx\" -DVERSION=\"2.0.23\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DX_DISPLAY_MISSING=1 -DSIZEOF_LONG=4 -DBUILD_DLL -I. -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -O3 -I/home/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/SDL2 -D_GNU_SOURCE=1 -D_REENTRANT -c SDL_framerate.c -o SDL_framerate.o >/dev/null 2>&1
SDL_rotozoom.c: In function '_colorkey':
SDL_rotozoom.c:91:21: error: 'SDL_PixelFormat' {aka 'struct SDL_PixelFormat'} has no member named 'colorkey'
   91 |    key = src->format->colorkey;
      |                     ^~
SDL_rotozoom.c: In function 'rotozoomSurfaceXY':
SDL_rotozoom.c:1071:19: error: 'SDL_SRCCOLORKEY' undeclared (first use in this function)
 1071 |  if (src->flags & SDL_SRCCOLORKEY)
      |                   ^~~~~~~~~~~~~~~
SDL_rotozoom.c:1071:19: note: each undeclared identifier is reported only once for each function it appears in
SDL_rotozoom.c:1201:4: warning: implicit declaration of function 'SDL_SetAlpha'; did you mean 'SDL_metal_h_'? [-Wimplicit-function-declaration]
 1201 |    SDL_SetAlpha(rz_dst, SDL_SRCALPHA, 255);
      |    ^~~~~~~~~~~~
      |    SDL_metal_h_
SDL_rotozoom.c:1201:25: error: 'SDL_SRCALPHA' undeclared (first use in this function)
 1201 |    SDL_SetAlpha(rz_dst, SDL_SRCALPHA, 255);
      |                         ^~~~~~~~~~~~
SDL_rotozoom.c: In function 'zoomSurface':
SDL_rotozoom.c:1496:24: error: 'SDL_SRCALPHA' undeclared (first use in this function)
 1496 |   SDL_SetAlpha(rz_dst, SDL_SRCALPHA, 255);
      |                        ^~~~~~~~~~~~
SDL_rotozoom.c:1509:27: error: 'SDL_SRCCOLORKEY' undeclared (first use in this function)
 1509 |   SDL_SetColorKey(rz_dst, SDL_SRCCOLORKEY | SDL_RLEACCEL, _colorkey(rz_src));
      |                           ^~~~~~~~~~~~~~~
Makefile:390: recipe for target 'SDL_gfxPrimitives.lo' failed
make[3]: *** [SDL_gfxPrimitives.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
SDL_rotozoom.c: In function 'shrinkSurface':
SDL_rotozoom.c:1656:33: error: 'SDL_SRCALPHA' undeclared (first use in this function)
 1656 |   result = SDL_SetAlpha(rz_dst, SDL_SRCALPHA, 255);
      |                                 ^~~~~~~~~~~~
SDL_rotozoom.c:1681:36: error: 'SDL_SRCCOLORKEY' undeclared (first use in this function)
 1681 |   result = SDL_SetColorKey(rz_dst, SDL_SRCCOLORKEY | SDL_RLEACCEL, _colorkey(rz_src));
      |                                    ^~~~~~~~~~~~~~~
Makefile:390: recipe for target 'SDL_rotozoom.lo' failed
make[3]: *** [SDL_rotozoom.lo] Error 1
SDL_gfxBlitFunc.c: In function '_SDL_gfxBlitRGBACall':
SDL_gfxBlitFunc.c:370:46: error: 'SDL_Surface' {aka 'struct SDL_Surface'} has no member named 'offset'
  370 |   info.s_pixels = (Uint8 *) src->pixels + src->offset + (Uint16) srcrect->y * src->pitch + (Uint16) srcrect->x * src->format->BytesPerPixel;
      |                                              ^~
SDL_gfxBlitFunc.c:378:46: error: 'SDL_Surface' {aka 'struct SDL_Surface'} has no member named 'offset'
  378 |   info.d_pixels = (Uint8 *) dst->pixels + dst->offset + (Uint16) dstrect->y * dst->pitch + (Uint16) dstrect->x * dst->format->BytesPerPixel;
      |                                              ^~
Makefile:390: recipe for target 'SDL_gfxBlitFunc.lo' failed
make[3]: *** [SDL_gfxBlitFunc.lo] Error 1

The above log doesn't seem to paste well:
https://dpaste.com/958YGVHD7

**Comment by mrfixit2001** [comment]
Same problem with SDL_image:

IMG_bmp.c: In function ‘LoadBMP_RW’:
IMG_bmp.c:401:23: error: ‘SDL_Color’ {aka ‘struct SDL_Color’} has no member named ‘unused’
  401 |     palette->colors[i].unused = 0;
      |                       ^
IMG_bmp.c:408:40: error: ‘SDL_Color’ {aka ‘struct SDL_Color’} has no member named ‘unused’
  408 |     SDL_RWread(src, &palette->colors[i].unused, 1, 1);
      |                                        ^
Makefile:467: recipe for target 'IMG_bmp.lo' failed

**Comment by mrfixit2001** [comment]
Just a theory - is maybe sdl-config telling the compiler to include the SDL2 include folder instead of the SDL include folder?

**Comment by mrfixit2001** [comment]
Ah - yes - I was correct - and you fixed it 8 days ago. Will close this now, sorry for the noise.

**Comment by mrfixit2001** [comment]
Spoke to soon haha sorry, testing latest commit, different error:
   ERROR: unsafe header/library path used in cross-compilation: '-I/usr/include/SDL'

Definitely related to sdl-config, looks like the fix from SDL2 to SDL also changed the prefix, so now the build system isn't including the proper path.

**Comment by mrfixit2001** [comment]
Reverting this commit resolves both sdl_gfx and sdl_image building, as long as I update the include path from SDL2 to SDL 
https://github.com/libsdl-org/sdl12-compat/commit/01e0b59b4662b9b840db143c735e4320904baa9e

Not sure why that would be required, as CMAKE_INSTALL_PREFIX is set to prefix either way. It definitely appears CMAKE_INSTALL_FULL_INCLUDEDIR isn't always passing the full path for some reason, but even if I use CMAKE_INSTALL_PREFIX/include inside sdl-compat.in it doesn't work. Strange.

Note: After that revert I do later then run into a compile error with sdl_sound regarding unsafe paths, but it gets thru everything else now. Not sure why it would pick up the proper path in other packages now, or why this works consistently with sdl1.2 and not sdlcompat. sdl_sound is now trying to use /usr/include/SDL and doesn't pick up my staging folder prefix /home/output/host/arm-buildroot-linux-gnueabihf/sysroot. sdl_sound is being passed the proper path in both "with-sdl-prefix" and "with-sdl-exec-prefix", and compiles fine against native sdl1.2.

**Comment by sezero** [comment]
You should set `CMAKE_INSTALL_PREFIX` to the proper location when
configuring sdl12-compat with cmake. When cross-configuring other
projects to build against sdl12-compat, you should set `SDL_CONFIG`
and-or `PKG_CONFIG_PATH` properly.

Unless I'm missing something, this bug looks like invalid: @icculus?

**Comment by mrfixit2001** [comment]
CMAKE_INSTALL_PREFIX is automagically set by the buildroot toolchain, but if there were build environment configuration issues then there would be build errors with native sdl 1.2. Everything builds fine against native sdl 1.2.

**Comment by mrfixit2001** [comment]
Maybe I need a patch similar to this in order to make it work in buildroot?

https://github.com/buildroot/buildroot/blob/master/package/taglib/0001-fix-taglib-config-file-for-cross-compiling-906.patch

**Comment by mrfixit2001** [comment]
Yep, this patch fixes all my compatibility issues. Not sure if it's toolchain / buildroot specific, but it appears the real missing key was @CMAKE_SYSROOT@. With this in place, everything compiles fine now and my build has continued on through SDL related packages.

`--- sdl-config.in.orig	2021-06-11 17:12:20.442391000 -0400
+++ sdl-config.in	2021-06-11 17:12:32.558391405 -0400
@@ -7,11 +7,11 @@
 
 # Copied and modified from SDL2's sdl2-compat.
 
-prefix=@CMAKE_INSTALL_PREFIX@
+prefix=@CMAKE_SYSROOT@@CMAKE_INSTALL_PREFIX@
 exec_prefix=${prefix}
 exec_prefix_set=no
-libdir=@CMAKE_INSTALL_FULL_LIBDIR@
-includedir=@CMAKE_INSTALL_FULL_INCLUDEDIR@
+libdir=${prefix}/lib
+includedir=${prefix}/include
 
 @ENABLE_STATIC_FALSE@usage="\
 @ENABLE_STATIC_FALSE@Usage: $0 [--prefix[=DIR]] [--exec-prefix[=DIR]] [--version] [--cflags] [--libs]"`

**Comment by icculus** [comment]
I think we're good here? I'm closing this; let me know if we should reopen.
