### ISSUE TITLE
Linapple emulator runs without graphics

### ISSUE THREAD

**Issue by mrfixit2001** [libsdl-org/sdl12-compat#110]
The behavior is that it runs, properly shows the logo for the emulator on the screen, and you can hear the game running in the background, but there's nothing displayed. Hitting F1 to display the help screen shows in the background that the graphics are being rendered, but they must be on another plane/level/window? This emulator runs properly against regular SDL1.2.

For reference, most of the rendering code I believe should be in these files:
https://github.com/linappleii/linapple/blob/master/src/Frame.cpp
https://github.com/linappleii/linapple/blob/master/src/Video.cpp

The following FIXME's are observed at runtime, in this order:
INFO: FIXME: there is never a parachute in SDL2, should we catch segfaults ourselves? (SDL_Init:1622)
INFO: FIXME: support SDL_INIT_EVENTTHREAD where it makes sense? (SDL_InitSubSystem:1594)
INFO: FIXME: Is subsystem init reference counted in SDL 1.2? (InitializeCDSubsystem:5989)
INFO: FIXME: Should we offer scaling for windowed modes, too? (SDL_SetVideoMode:3823)
INFO: FIXME: currently ignores SDL_WINDOWID, which we could use with SDL_CreateWindowFrom ...? (SDL_SetVideoMode:3840)
INFO: FIXME: handle SDL_ANYFORMAT (SDL_SetVideoMode:3854)
INFO: FIXME: There's an environment variable to choose a display (SDL_SetVideoMode:3861)
INFO: FIXME: don't do anything if the window's dimensions, etc haven't changed. (SDL_SetVideoMode:3888)
INFO: FIXME: we need to preserve VideoSurface12 (but not its pixels), I think... (SDL_SetVideoMode:3889)
INFO: FIXME: setup screen saver (SDL_SetVideoMode:4128)
INFO: FIXME: write me (SDL_EnableKeyRepeat:5383)
INFO: FIXME: Respect 1.2 environment variables for defining format here. (SDL_OpenAudio:6705)
INFO: FIXME: if this fails, we need to deal with app callback or cd-rom no longer working (OpenSDL2AudioDevice:6649)
INFO: FIXME: deal with failure in here (OpenSDL2AudioDevice:6658)
INFO: FIXME: Cleanup from failures in here (SDL_OpenAudio:6741)
INFO: FIXME: what's the difference between RESIZED and SIZE_CHANGED? (EventFilter20to12:2643)
INFO: FIXME: This should only save the dst rect in use (SaveDestAlpha:4156)

Happy to test any theories or ideas if you pass them along

**Comment by mrfixit2001** [comment]
FYI - it's related to threading. if I restrict the emulator to not using multiple threads then it renders properly

**Comment by icculus** [comment]
This is working for me in X11; is this failing on a Raspberry Pi or something?

**Comment by mrfixit2001** [comment]
I'm not using X11, I'm on GLES + GBM (Mali). Yes it's on an ARM board, a Rockchip 3328.

**Comment by mrfixit2001** [comment]
Just to further the documentation on the issue - the setting to force a single thread is in the conf file named "Singlethreaded", this must be set to 1 in order for the emulator to work properly with sdlcompat

**Comment by icculus** [comment]
Can you export the environment variable `SDL_RENDER_DRIVER=software` and see if it makes a difference?

**Comment by mrfixit2001** [comment]
Tested and no go.
Even went as far as adding "SDL_RENDER_DRIVER=software" to the command line as a prefix to linapple. Same issue.

**Comment by icculus** [comment]
Testing this on X11 and I can reproduce it now.  We just worked around this for a specific app in #182, but you likely don't have the luxury of a non-OpenGL path for the same fix, but let me see what I can do now that I can reproduce this here.

**Comment by icculus** [comment]
I just fixed this to work on X11, and I believe this will fix it on your platform, too.

If the latest sdl12-compat (and possibly SDL 2.24.0) doesn't fix your issue, please let me know and I'll reopen this bug. Thanks!
