### ISSUE TITLE
sdl12-compat doubles all key strokes in UT2004

### ISSUE THREAD

**Issue by cosmosgit** [libsdl-org/sdl12-compat#119]
linux 5.12.14-200.fc33.x86_64
I built /lib64/libSDL-1.2.so.1.2.50 from git on July 7 and changed symlink to { ln -s libSDL-1.2.so.1.2.50 libSDL-1.2.so.0 }.

Problem: All key strokes entered into UT2004 are doubled.
Example:  Command r
  Type abcd<enter>
  Resultant team say is raabbccdd

Resetting symlink to { ln -s libSDL-1.2.so.0.11.4 libSDL-1.2.so.0 } restores normal behavior.
Behavior is the same under X Windows and Wayland.

**Comment by sulix** [comment]
This should be fixed now.

**Comment by sezero** [comment]
No response from bug reporter: Closing this after commit https://github.com/libsdl-org/sdl12-compat/commit/1cc3061c06877a7ee4277187aa59dcca755e5a7f
