### ISSUE TITLE
Strange behaviour of SDL_SetVideoMode when using it to change between FULL_SCREEN and Windowed

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/sdl12-compat#12]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Patch to resolve described issue. (tip.patch, text/plain, 2019-03-22 20:33:24 +0000, 1143 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3708)
* [A video showing game behaviour with submitted patch. (patched.mp4, application/octet-stream, 2019-03-22 20:57:46 +0000, 7073734 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3709)
* [A video showing game behaviour without patch (unpatched.mp4, application/octet-stream, 2019-03-22 20:59:11 +0000, 4241145 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3710)

**Reported in version:** unspecified
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2019-03-22 20:33:24 +0000, Dario wrote:

> Created attachment 3708
> Patch to resolve described issue.
> 
> I have a game that uses SDL_SetVideMode to run on SDL_FULLSCREEN mode on a 2560x1440. The non-scaled resolution of the game when running in fullscreen is 1280x720.
> 
> The game allows using non-full screen mode, and with GDB I have seen it results invoking SDL_SetVideoMode again without the SDL_FULLSCREEN flag. The target size of the window is 640 x 360.
> 
> For some reason, when switching from full screen to windowed, the "surface" does not get resized. It remains at 2560x1440 which results in a clipped area.
> 
> When SDL_SetVideoMode is invoked a second time with the 640x360 Windowed, the contents are resized correctly.
> 
> I was able to overcome this problem by forcing a EnvVidModeCreate() when the target width and height does not match the width and height that VideoSurface12 contained. See patch.
> 
> There might be however a better way of resolving this. I tried to do a lot of debugging but this is as far I could get :).

On 2019-03-22 20:57:46 +0000, Dario wrote:

> Created attachment 3709
> A video showing game behaviour with submitted patch.

On 2019-03-22 20:59:11 +0000, Dario wrote:

> Created attachment 3710
> A video showing game behaviour without patch

**Comment by sezero** [comment]
@icculus: Is the patch OK?

**Comment by slouken** [comment]
This seems correct to me.

**Comment by sezero** [comment]
Fixed as of commit e3bf3c6d2f
