### ISSUE TITLE
macOS: With DOSBox there is an audible pop on init and closing

### ISSUE THREAD

**Issue by DominusExult** [libsdl-org/sdl12-compat#122]
This is not present with normal SDL 1.2x and also not with the SDL12compat "loopwave".
[new.m4a.zip](https://github.com/libsdl-org/sdl12-compat/files/6841830/new.m4a.zip)

**Comment by icculus** [comment]
Built DOSBox from svn trunk, pointed it at sdl12-compat and run it and it reproduces here, as soon as the C: prompt comes up.

The pop is coming directly from the DOSBox audio callback, fwiw. Added this to sdl12-compat:

```diff
diff --git a/src/SDL12_compat.c b/src/SDL12_compat.c
index 5411ee3..e0855b8 100644
--- a/src/SDL12_compat.c
+++ b/src/SDL12_compat.c
@@ -7792,6 +7792,7 @@ AudioCallbackWrapper(void *userdata, Uint8 *stream, int len)
         while (SDL20_AudioStreamAvailable(data->app_callback_stream) < len) {
             SDL20_memset(data->mix_buffer, data->app_callback_format.silence, data->app_callback_format.size);  /* SDL2 doesn't clear the stream before calling in here, but 1.2 expects it. */
             data->app_callback_format.callback(data->app_callback_format.userdata, data->mix_buffer, data->app_callback_format.size);
+{ static FILE *io = NULL; if (!io) { io = fopen("callback.raw", "wb"); } if (io) { fwrite(data->mix_buffer, 1, data->app_callback_format.size, io); fflush(io); } }
             if (SDL20_AudioStreamPut(data->app_callback_stream, data->mix_buffer, data->app_callback_format.size) == -1) {  /* probably out of memory if failed */
                 break;  /* this will make the AudioStreamGet call fail. */
             }
```

And here's wht callback.raw looks like after running:

<img width="665" alt="Screen Shot 2021-12-14 at 4 37 12 PM" src="https://user-images.githubusercontent.com/673562/146083380-d348cbb3-093d-4658-9001-96eae695c7a4.png">

...those two squares are the pops, so it's not a conversion inside SDL that's wrong or playback itself.

I don't know why this happens with sdl12-compat, and I haven't verified that classic SDL 1.2 doesn't trigger this, yet.

**Comment by icculus** [comment]
Seems to correspond with this log message I uncommented in DOSBox's sources, but I could be imagining that:

```
Full underrun need 1024, have 1003, min 1102
```

If you pause the process with ctrl-z in a terminal, you'll get more pops when you resume. Sometimes I can trigger just by Option-Tabbing to another process.

So this is something gone wrong in DOSBox's underrun handler, I think.

**Comment by icculus** [comment]
> I believe SDL 1.2 zeroes the buffers before passing them to the application, where in SDL 2.0 we don't do that, as an optimization.

sdl12-compat zeroes the buffer before handing to the app callback, for just this reason.  :)

**Comment by slouken** [comment]
> > I believe SDL 1.2 zeroes the buffers before passing them to the application, where in SDL 2.0 we don't do that, as an optimization.
> 
> sdl12-compat zeroes the buffer before handing to the app callback, for just this reason. :)

Aha! :)

**Comment by icculus** [comment]
> sdl12-compat zeroes the buffer before handing to the app callback, for just this reason. :)

Wait, it's not _zeroing_ it...that's the problem. The "silence" field is wrong for some reason.
