### ISSUE TITLE
Quake IV lacks stencil shadow volumes

### ISSUE THREAD

**Issue by eukara** [libsdl-org/sdl12-compat#126]
Running **Quake4 V1.4.2 linux-x86 Jun 15 2007** and sdl12-compat from git (**87c7e29**) compiled for 32-bit.

![shot00001](https://user-images.githubusercontent.com/40036380/128073634-1fe22200-563d-471e-b0d3-42b26ac5582f.png)
![shot00002](https://user-images.githubusercontent.com/40036380/128073641-6db403d6-f361-42d3-a58f-d261d4376b78.png)

Not a whole lot to say here, other than Quake IV completely lacking shadows. First shot is real SDL 1.2, second is sdl12-compat.
Also sorry for the upside down images, I forgot the games TGA screenshots wouldn't automatically get flipped by mogrify.

![shot00003](https://user-images.githubusercontent.com/40036380/128074192-1a9e8b98-6e08-47c1-ab90-a6f5ee78289f.png)

**r_showShadows** reveals that the stencil shadow volumes are being calculated and cut properly (compared that too with old 1.2 and they look identical)

![shot00004](https://user-images.githubusercontent.com/40036380/128074646-a1a55f53-46f0-4f2e-9b74-34ff5f1e86ac.png)

Interestingly enough, toggling **r_useShadowVertexProgram** to be set to 0 will make something show. It's not right (old SDL 1.2 renders this properly) but at least it shows that it's doing something.

I recently went over and set-up all my games to use sdl12-compat and noticed this right away when booting up Quake IV. I suspected Prey (1.4.119 linux-x86 Nov 26 2008) to be potentially affected by this as well, but that does not seem to be the case. It looks just fine.

**Comment by icculus** [comment]
I believe we have fixed this, probably with either OpenGL scaling getting correct render buffers formats or with SDL_GL_GetAttribute no longer returning 0 for various sizes.

So I guess either Quake 4 needed an alpha channel on the window framebuffer, or it incorrectly believed there was no stencil buffer. Either way, it appears to work now.

![shot00001](https://user-images.githubusercontent.com/673562/145681275-128b9598-1dbb-4093-8e7e-0ae9f691abb1.jpg)
