### ISSUE TITLE
Non-US Keyboard layouts not supported

### ISSUE THREAD

**Issue by DanielGibson** [libsdl-org/sdl12-compat#135]
Just to make sure this is in a proper issue and not just in comments on a closed PR: SDL1.2 *did* support non-US layouts. Maybe not as well as SDL2 does, but contrary to the assumptions in #97 it did **not** just use scancodes.

(Pasting my comment from #97:)

For example, look at SDL1.2's `X11_TranslateKeycode()`: https://github.com/libsdl-org/SDL-1.2/blob/main/src/video/x11/SDL_x11events.c#L1155
It translates the X11 KeyCode (which is kinda like a SDL scancode) to a X11 KeySym (which is supposed to be the thing printed on the keyboard's keycaps, i.e. like SDL2 SDL_KeyCode, see https://tronche.com/gui/x/xlib/input/keyboard-encoding.html) and then translates that to a `SDLKey` which is used in `SDL_keysym::sym` (see https://github.com/libsdl-org/SDL-1.2/blob/main/src/video/x11/SDL_x11events.c#L606 ).

So `SDLKey` indeed is based on the name of (printed on) the key and not the scancode.

So https://github.com/libsdl-org/sdl12-compat/blob/36a09e450a007c86ed0f91812fbbba0d783be120/src/SDL12_compat.c#L2564 should be turned to `#if 1` and *maybe* some additional work could be done to support more (non-ASCII) keys; I'm not sure how exactly those (e.g. German Umlaut keys) were handled in SDL1.2.

I hope I'll get around to look into this a bit, but I don't know when so I can't promise anything right now.

**Comment by sulix** [comment]
So, I did test this a bit with different keyboard layouts, and the conclusion I came to was that, while SDL 1.2 does support keyboard layouts, it's very often broken (it didn't work at all for me if there are multiple configured layouts), and more applications broke with it than without it. So I've sort-of been treating SDL 1.2 as not supporting keyboard layouts (except for the "unicode" value), and the X11 backend's support for them is more of a bug.

Similarly, my attempt at testing this on windows also had SDL 1.2 not take keyboard layout into account. Indeed, there appears to be some explicit code to force the US layout:
https://github.com/libsdl-org/SDL-1.2/blob/main/src/video/windib/SDL_dibevents.c#L547

Now it's possible (maybe even probable) that this is something specific to the configurations I tried (having multiple configured layouts, or something like that), but in almost all of the different cases I tried, SDL 1.2 didn't take the layout into account. Unfortunately, I guess the "single, non-US layout" is probably the main exception here, and I agree that it's an important one.

However the fact that some applications rely on a scancode-like behaviour, (e.g. DOSBox, which has its own keyboard layout configuration), I still think that having scancodes passed through like this is at least as correct as using the layout-specific keycodes.

I'm definitely all for making this configurable, though. I agree that keycodes being, well, keycodes is the nicer solution, but using scancodes seemed to fix a lot more things than it broke in practice.

**Comment by DanielGibson** [comment]
> https://github.com/libsdl-org/SDL-1.2/blob/main/src/video/windib/SDL_dibevents.c#L547

That's [Windows CE](https://en.wikipedia.org/wiki/Windows_Embedded_Compact) specific, i.e. mostly irrelevant, I think.

> I guess the "single, non-US layout" is probably the main exception here, and I agree that it's an important one.

Yes, this is what most **users** with non-US keyboards will have - I mean you usually only have multiple keyboard layouts configured for testing.

As far as I remember, it always worked ok-ish with my German QWERTZ keyboards, it's definitely possible that it works less well with other layouts. So if SDL1.2 software didn't support other layouts at all it was already broken back then.
Nevertheless, having a environment variable to switch between using scancodes and using keycodes would probably be the best solution (though I'd argue keycodes should be default).

**Comment by sulix** [comment]
> That's [Windows CE](https://en.wikipedia.org/wiki/Windows_Embedded_Compact) specific, i.e. mostly irrelevant, I think.

Are you sure? It's in the #if**n**def part of the code: so it looks to me like it's non-CE versions of windows which are forced to use US layout.

> Yes, this is what most **users** with non-US keyboards will have - I mean you usually only have multiple keyboard layouts configured for testing.

Makes sense. I don't want to be needlessly anglo-centric and force the US layout on everyone. I'll try to put together a patch which lets you switch when I have some time over the weekend. I still get the impression from the windows stuff and the explicit choice to treat these as scancodes in DOSBox and a few other games that the X11 backend doing layout translation is the outlier here, particularly since layout translation does work for the unicode text input, so the most important case of text input should (in theory) be covered.

**Comment by DanielGibson** [comment]
> Are you sure? It's in the #ifndef part of the code: so it looks to me like it's non-CE versions of windows which are forced to use US layout.

Damn, you're right, I missed the `n` :-/

I don't remember SDL on Windows using the wrong keyboard layout, but then again I've been using Linux for almost 20y now so I probably didn't use SDL1.2 much on Windows.

Should the default on using scancode vs keycode be OS specific?
OTOH, is sdl12-compat even relevant on non-Linux platforms? Probably SDL1.2 still works ok on Windows, old Mac games don't work anymore because they switched their CPU architecture multiple times since then and there's probably not many proprietary games for other platforms that need SDL1.2?

**Comment by DanielGibson** [comment]
Apparently on Windows this change (to always assume US-layout) were done so the WinDIB and DirectX backends are consistent with each other (apparently the SDL1.2 DirectX backend never supported keyboard layouts): https://github.com/libsdl-org/SDL-1.2/issues/95

**Comment by sezero** [comment]
@DanielGibson: does it behave as of latest git with PR #136 merged?

**Comment by sulix** [comment]
Note that the PR #136 shouldn't change the default behaviour at all — it just adds the ``SDL12COMPAT_USE_KEYBOARD_LAYOUT`` hint to change it without a recompile.

There's still the possibility of changing the default if we have to. Though I suspect if we do we'll want to at least make it platform-specific, given that SDL 1.2 very explicitly doesn't take the layout into account on Win32.

**Comment by sezero** [comment]
Well it _does_ change behavior: it now work as SDL1.2 does on my Turkish-F layout.
The reason is you _possibly_ intended
`TranslateKeyboardLayout = (layout_env && SDL20_atoi(layout_env)) ? SDL_TRUE : SDL_FALSE;`
at line 1737 (https://github.com/libsdl-org/sdl12-compat/blob/main/src/SDL12_compat.c#L1737) and not
`TranslateKeyboardLayout = (!layout_env || SDL20_atoi(layout_env)) ? SDL_TRUE : SDL_FALSE;`
But I'm happy with the result :)

Off-topic: we should document `SDL12COMPAT_xxx` environment vars.

**Comment by slouken** [comment]
It's likely that we need to default the variable differently between Windows and Linux to preserve SDL 1.2 behavior.

**Comment by sezero** [comment]
How does mac (should) behave?

**Comment by sulix** [comment]
I've sent out PR #137 which makes this hint default to TRUE on everything except Win32.

From my look at the code, it seems like Mac should support keyboard layouts (though I don't have a mac to test it):
https://github.com/libsdl-org/SDL-1.2/blob/main/src/video/maccommon/SDL_macevents.c#L590

**Comment by sezero** [comment]
This should be fixed as of current git with #137 merged. Please open new tickets for any possible new issues.

**Comment by DanielGibson** [comment]
I just tested this, it indeed works as expected (except for some keys like umlauts not working, but I have an idea for that).

Thanks for making this work! :)

**Comment by DanielGibson** [comment]
I just noticed that the SDL1.2 scancode for SDL_SCANCODE_NONUSBACKSLASH is wrong, because of
`CASESCANCODE20TO12(NONUSBACKSLASH, 0x33, 0x2A);` and
`CASESCANCODE20TO12(BACKSLASH, 0x33, 0x2A);` i.e. both keys are handled the same, even if they're different keys.
On German keyboards, `NONUSBACKSLASH` is `<>|` (the key between left shift and Y) and `BACKSLASH` is `#'` (the key between Enter, Right Shift and Ä).

On Linux the correct SDL1.2 scancode for `NONUSBACKSLASH` is `0x5E` (that's what a real libsdl1.2 gives me), **but what is it for Mac?**

Does anyone of have a Mac and a Keyboard with ISO layout? Can you post the scancode a real libsdl1.2 gives you for the key that's right of **Left Shift** (and left of SDL_SCANCODE_Z, often Z or Y)?
Then I can include that in my fix that I'll create a PR for.

**Comment by DanielGibson** [comment]
Ok, it seems like it just uses the Mac scancodes and I found an overview of them here: https://stackoverflow.com/a/16125341
So on ISO-layouts that key should be 0x32 - which sucks, because on Apple ANSI-layouts 0x32 is SDL_SCANCODE_GRAVE, i.e. the key between Esc, Tab and 1.. on Apple ISO layouts that key is 0x0A.

So maybe it's best (or at least good enough) to keep on mapping SDL_SCANCODE_GRAVE to 0x32 and map SDL_SCANCODE_NONUSBACKSLASH to 0x0A instead - then at least both keys have a valid and different scancode at all (as far as I can tell, 0x0A isn't used at all on ANSI-layouts).

**Comment by DanielGibson** [comment]
I created a "little" patch: https://github.com/libsdl-org/sdl12-compat/pull/139
