### ISSUE TITLE
Unable to link under OS X

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/sdl12-compat#14]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** unspecified
**Reported for operating system, platform:** macOS 10.13, x86_64

# Comments on the original bug report:

On 2019-04-11 07:29:05 +0000, C.W. Betts wrote:

> After working around the issue of SDL2 header locations, it fails to link under Mac, complaining about a missing function. The function can be found in src/SDL12_compat_objc.m. After fixing that, it still doesn't link because of a couple new undefined symbols, both related to Objective-C. Telling the linker to link against the AppKit fixes this issue.

**Comment by sezero** [comment]
macOS build/linkage is fixed as of commit 9f7e7aa9935c
