### ISSUE TITLE
[UT2004] Can't type certain symbols in-game

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/sdl12-compat#15]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** unspecified
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2019-08-04 13:50:27 +0000,  wrote:

> First of all, thanks for working on this!
> I was playing around with this fun little thing and noticed the following problem:
> You can't type certain symbols, like colon ':', or question mark '?' while playing UT2004 64-bit for linux. This makes difficult connecting to servers, as you can't specify port.
> Haven't tested with other games so far.
> 
> OS: openSUSE 15.1
> Package source: https://build.opensuse.org/package/show/home:khnazile:libSDL12-compat/libSDL12-compat

**Comment by sezero** [comment]
Dup of https://github.com/libsdl-org/sdl12-compat/issues/17
