### ISSUE TITLE
SDL_GL_GetAttribute doesn't work

### ISSUE THREAD

**Issue by sezero** [libsdl-org/sdl12-compat#150]
Running testgl program against SDL-1.2-git:
```
SDL_GL_RED_SIZE: requested 5, got 8
SDL_GL_GREEN_SIZE: requested 5, got 8
SDL_GL_BLUE_SIZE: requested 5, got 8
SDL_GL_DEPTH_SIZE: requested 16, got 24
SDL_GL_DOUBLEBUFFER: requested 1, got 1
key 'q' pressed
key 'escape' pressed
3489.95 FPS
```

Against sdl12-compat + SDL2-git:
```
SDL_GL_RED_SIZE: requested 5, got 0
SDL_GL_GREEN_SIZE: requested 5, got 0
SDL_GL_BLUE_SIZE: requested 5, got 0
SDL_GL_DEPTH_SIZE: requested 16, got 0
SDL_GL_DOUBLEBUFFER: requested 1, got 0
testgl: SDL error 'OpenGL error: GL_INVALID_ENUM'
app gained input focus
key 'q' pressed
key 'escape' pressed
2669.96 FPS
```

And that `GL_INVALID_ENUM` error is something else.

**Comment by sezero** [comment]
Running it with `SDL12COMPAT_OPENGL_SCALING=0` makes it work, though:
```
SDL_GL_RED_SIZE: requested 5, got 8
SDL_GL_GREEN_SIZE: requested 5, got 8
SDL_GL_BLUE_SIZE: requested 5, got 8
SDL_GL_DEPTH_SIZE: requested 16, got 24
SDL_GL_DOUBLEBUFFER: requested 1, got 1
testgl: SDL error 'Surface doesn't have a colorkey'
app gained input focus
key 'q' pressed
key 'escape' pressed
3707.44 FPS
```

**Comment by icculus** [comment]
Ok, this is happening because in SDL2's SDL_GL_GetAttribute, we are calling...

```c
glGetFramebufferAttachmentParameteriv(GL_FRAMEBUFFER, GL_BACK_LEFT, GL_FRAMEBUFFER_ATTACHMENT_RED_SIZE /* or whatever */, &value);
```

My guess is this works on the window framebuffer (FBO 0), but not when we have our scaling FBO bound.

**Comment by icculus** [comment]
I'm going to work around this by temporarily binding FBO 0 before calling into SDL20_GL_GetAttribute, so it will work with <= 2.0.18, but this is an SDL2 bug imho and we should fix _that_ for 2.0.20.

**Comment by sezero** [comment]
Is the Broken Sword fix (#149) affected? I.e.:
https://github.com/libsdl-org/sdl12-compat/blob/main/src/SDL12_compat.c#L4874-L4881

The Set function isn't affected, isn't it?

**Comment by icculus** [comment]
We haven't bound the FBO yet at that point, so it works.

We could query through the 1.2 interface just to be safer, though.

**Comment by icculus** [comment]
(The SDL2 bug is fixed now, but this workaround will remain in sdl12-compat to deal with SDL2 builds earlier that 2.0.20.)
