### ISSUE TITLE
Implement X11_KeyToUnicode

### ISSUE THREAD

**Issue by icculus** [libsdl-org/sdl12-compat#153]
> IIRC, there was a Loki game (I forget which), which uses X11_KeyToUnicode, which was an internal function in the X11 backend. At the time, it was non-trivial to mark non-static symbols in shared libraries as private, so Loki used one of them they shouldn't have.
>
> ...I want to say it was Heavy Gear II, but I could be wrong.
>
> Actually, it appears to be the Torque Engine having this issue in more modern times (although perhaps they inherited this from Tribes 2?)...this means Space Pirates and Zombies, on Steam, will need this symbol exported, if nothing else.

_Originally posted by @icculus in https://github.com/libsdl-org/sdl12-compat/issues/143#issuecomment-987503809_

**Comment by icculus** [comment]
> this means Space Pirates and Zombies, on Steam, will need this symbol exported, if nothing else.

Turns out this isn't true:

```c
// !!! FIXME: this isn't right, but I'm removing the private SDL function call.
   AsciiTable[tkey].lower.ascii = tolower((int) SDLkey);
   AsciiTable[tkey].upper.ascii = toupper((int) SDLkey);
   AsciiTable[tkey].goofy.ascii = tolower((int) SDLkey);
```

I future-proofed it ten years ago.  :)

I made the same change to Frozen Synapse, which is also a Torque Engine game. I'm not sure what else is a) Torque based, b) on Steam, c) for Linux that d) I didn't port.  :)

But we need _something_ in case something shows up...I don't think SDL2 exposes an equivalent of XLookupString() info outside of TEXTINPUT events, but probably most things using this were going to end up broken outside of US English and ASCII anyhow, maybe the most basic "cast the SDLKey to an ASCII char and be done with it" is the right approach until (and if) bug reports arrive?

**Comment by DanielGibson** [comment]
This probably only works for ASCII and Latin-1, because SDL1.2 mapped all those  Latin-* keys to to the same range (0xA0 to 0xFF, aka SDLK12_WORLD_0 to SDLK12_WORLD_95) by truncating their X11 keycodes to the lowest byte, see also my endless switch/case in `Keysym20to12()`.

So *maybe* you could get away with handling ASCII and Latin-1 with and without shift (AltGr not working on German keyboards to to create chars like "{[]}\~" might suck for some usecases, but still better than nothing)?
Probably the hardest part to get right is the non-letter keys (like 0-9, `.`, `,`, `#` etc), because their shifted char depends on the keyboard layout - and maybe assuming US-ANSI layout is good enough for them (or at least better than nothing), but I don't know what exactly it's used for in Torque and whatever other engines use it.

**Comment by DanielGibson** [comment]
BTW, someone came up with a legit (IMHO) usecase for a function like this: emulators for old computers like C64 that had their own keyboard layouts. See https://discourse.libsdl.org/t/sdl-2-how-to-read-shift-x-keys/21238/12 and following

If a function that took SDL_Keycode (or SDL_Scancode; those could be converted as needed) and modifiers and returns a Unicode char (based on the current keyboard layout) was added to SDL2, it probably could be used for X11_KeyToUnicode() as well :)

**Comment by icculus** [comment]
> If a function that took SDL_Keycode (or SDL_Scancode; those could be converted as needed) and modifiers and returns a Unicode char (based on the current keyboard layout) was added to SDL2, it probably could be used for X11_KeyToUnicode() as well :)

This is a landmine one definitely does not want to step on.  :)

**Comment by icculus** [comment]
The extremely naive implementation is in revision control.

This handles upper and lowercase low-ASCII letters, and most other items below 127 will just cast directly to Uint16. Everything else gets a zero. You can add this to testwm.c to test:

```diff
diff --git a/test/testwm.c b/test/testwm.c
index 0486156..1c8ff3f 100644
--- a/test/testwm.c
+++ b/test/testwm.c
@@ -235,6 +235,14 @@ static void PrintKey(const SDL_keysym *sym, int pressed)
 #endif
                }
        }
+
+#if 1
+    {
+        extern DECLSPEC Uint16 SDLCALL X11_KeyToUnicode(SDLKey, SDLMod);
+        printf(" [U%u]", X11_KeyToUnicode(sym->sym, sym->mod));
+    }
+#endif
+
        print_modifiers();
        printf("\n");
 }
```

Obviously this isn't perfect but I suspect it's sufficient. Small patches to improve this are welcome, but use-cases for this are small, it was never a public API, and so this is hopefully Good Enough and we won't waste code on it further.

**Comment by sezero** [comment]
Do we want this in non-unix builds?

**Comment by slouken** [comment]
> Do we want this in non-unix builds?

In the comment:
"As this isn't X11-specific, we supply it globally, so x11 binaries can transition
   to Wayland, and if there's some wildly-misbuilt win32 software, they can call it
   too. :)"

**Comment by sezero** [comment]
So that means no, we only build it for unices - will push a patch shortly.

**Comment by DanielGibson** [comment]
As far as I can tell, "if there's some wildly-misbuilt win32 software, they can call it too." means that it should be available everywhere

**Comment by sezero** [comment]
> As far as I can tell, "if there's some wildly-misbuilt win32 software, they can call it too." means that it should be available everywhere

So wildly misbuilt that includes x11 code??

**Comment by icculus** [comment]
The added preprocessor test is fine with me.
