### ISSUE TITLE
Need help building the Win32 binary SDL.dll

### ISSUE THREAD

**Issue by Spatzendame** [libsdl-org/sdl12-compat#159]
Hello,

I've already red all the tutorials, but I still failed to build the binaries using the latest Microsoft Visual Studio 2022 Community.
I get errors in the building process and then no dll will be built. What am I doing wrong?
Please can someone explain to me exactly how to build the SDL.dll ?

I don't know how to link the SDL2_INCLUDE_DIR to CMake etc.

Maybe someone here can build the dll for me from this source code here?

Thank you very much for your help.

**Comment by sezero** [comment]
Here are windows x86 and x64 builds from git master:
[win32-x86.zip](https://github.com/libsdl-org/sdl12-compat/files/8016069/win32-x86.zip)
[win64-x64.zip](https://github.com/libsdl-org/sdl12-compat/files/8016071/win64-x64.zip)

**Comment by Spatzendame** [comment]
Thank you so much, Mr. Sezer! I'm really happy to have these .dlls.
If you could explain how to configure the VS2022 to get a proper build of SDL12-compat, I can do it for myself in the future when you update the source code or SDL2.0 which have to get linked. I want to understand how to build it myself in the future. Unfortunately there is no tutorial for it step-by-step. Maybe you can tell me, if it's not too complicated?

**Comment by sezero** [comment]
Questions like this are best asked / discussed at https://discourse.libsdl.org/
But well, let's try: As the readme says, you need SDL2 headers to build this.
So, run cmake, let it fail, then edit `SDL2_INCLUDE_DIR` so that it points to
the SDL2 headers directory and re-configure. The rest should be OK.

**Comment by Spatzendame** [comment]
Thank you, I got it! Here is exactly what people have to do:

Download SDL2-devel-VC release
Extract it to C:\SDL2

Start CMake, check the option "Advanced", press Configure, let it fail
Edit SDL2_INCLUDE_DIR = C:\SDL2\include
Edit SDL2_LIBRARY = C:\SDL2\lib\x86\SDL2.lib

Configure again, Generate

Start SDL12-compat.sln with Microsoft Visual Studio, set everything to "Release Win32", rebuild everything


This could help everyone. I just wonder why my SDL.dll is 189 kB while that one you sent me is 162 kB.

**Comment by sezero** [comment]
> Is everything correct?

Seems so, yes

> Maybe you add this information to the main page of the project so that it helps everyone.

Possibly a job for @icculus 

> I just wonder why my SDL.dll is 189 kB while that one you sent me is 162 kB.

Difference of compiler (mine were built using mingw gcc-4.5.4)

**Comment by sezero** [comment]
Also note that you can build it from the console without cmake if you want to: cd into `src` directory, read `Makefile.vc`
