### ISSUE TITLE
Wolf4SDL loses inputs when mouse grabbed

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/sdl12-compat#16]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** unspecified
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2019-10-11 22:57:08 +0000, Rohit Nirmal wrote:

> Wolf4SDL build from this git repo: https://github.com/mozzwald/wolf4sdl
> 
> When Wolf4SDL is run with sdl12-compat in the default fullscreen mode or with the --windowed-mouse command line option, using the Up and Down arrows in the menu does nothing (Enter and Escape work though). Additionally, the player is always moving during gameplay, even when the mouse and keyboard aren't used.
> 
> The problem seems to be related to the SDL_WM_GrabInput call made here: https://github.com/mozzwald/wolf4sdl/blob/master/id_in.cpp#L395
> 
> In normal SDL 1.2, moving the mouse up and down can move the menu cursor. I suspect sdl12-compat is somehow misreporting mouse movement when the mouse is grabbed.

**Comment by sezero** [comment]
Reproduced this one. @icculus?

**Comment by icculus** [comment]
I'll see if I can sort this out.

**Comment by icculus** [comment]
Reproduces for me, too. Digging in.

**Comment by rohit-n** [comment]
I forgot about this bug! Thanks for fixing it.
