### ISSUE TITLE
pkg-config drop-in compatibility with sdl package?

### ISSUE THREAD

**Issue by traversaro** [libsdl-org/sdl12-compat#162]
Hi everyone, thanks a lot for your work.

I have a question related to drop-in compatibility of the `sdl12-compat` library with `sdl`. From the pkg-config point of view, once you install `sdl12-compat` version https://github.com/libsdl-org/sdl12-compat/commit/406decc52a88f48dc4e534681ced8f72af84544c with pkg-config 0.29.2, the commands:
~~~
pkg-config --cflags sdl
~~~
and
~~~
pkg-config --libs sdl
~~~
do not return anything. Is this intentional? 

I indeed noticed that a `sdl12_compat` pkg-config package is installed, and that the `sdl12_compat.pc` contains a line:
~~~
Provides: sdl = 1.2.50
~~~

However, I am not sure if the `pkg-config` tool process that line, as I could not find any documentation or code related to this field. 

Also the command:
~~~
pkg-config --print-provides sdl12_compat
~~~
Just prints:
~~~
sdl12_compat = 1.2.50
~~~

So it seems like that the `Provides` field is ignored?

**Comment by smcv** [comment]
> However, I am not sure if the pkg-config tool process that line, as I could not find any documentation or code related to this field.

I don't think it does.

In the Debian packaging that's on its way into experimental, I created a symbolic link `sdl.pc -> sdl12_compat.pc`, and that seems to result in the right thing happening.

**Comment by Conan-Kudo** [comment]
`pkgconf` (used by RHEL, Fedora, Mageia, OpenMandriva, and openSUSE) reads the `Provides:` field properly. I suspect legacy `pkg-config` never finished implementing it.
