### ISSUE TITLE
[typo] test readme typo

### ISSUE THREAD

**Issue by arrowgent** [libsdl-org/sdl12-compat#172]
i could do a PR, just not that big of a deal to get pushed through as a contributor for such a small item

https://github.com/libsdl-org/sdl12-compat/blob/main/test/README

testhread = testthread

great work.  currently testing some things
thanks

**Comment by sezero** [comment]
The source has always been `testhread.c`, the binary is still named the same `testhread` in real SDL-1.2, but @icculus seems to have _fixed_ it here :)

**Comment by arrowgent** [comment]
the file created itself is `testthread`

libsdl12-compat/sdl12-compat/build $ ll testthread
`-rwxrwxr-x 1 catbox catbox 13072 Mar 17 08:05 testthread*`

like i said, not a big oops so i'll let you maintainers handle it sometime
