### ISSUE TITLE
Allow retrieval of SDL_Window when version.major == 2

### ISSUE THREAD

**Issue by kjliew** [libsdl-org/sdl12-compat#186]
Here's the proposed patch
```
diff -ru orig/sdl12-compat-release-1.2.52/include/SDL/SDL_syswm.h ./src/sdl12-compat-release-1.2.52/include/SDL/SDL_syswm.h
--- orig/sdl12-compat-release-1.2.52/include/SDL/SDL_syswm.h    2022-03-03 06:56:56.000000000 -0800
+++ ./src/sdl12-compat-release-1.2.52/include/SDL/SDL_syswm.h   2022-05-06 14:33:23.409605790 -0700
@@ -109,7 +109,7 @@
         typedef struct SDL_SysWMinfo
         {
             SDL_version version;
-            int data;
+            void *data;
         } SDL_SysWMinfo;

 #       include "close_code.h"
diff -ru orig/sdl12-compat-release-1.2.52/src/SDL12_compat.c ./src/sdl12-compat-release-1.2.52/src/SDL12_compat.c
--- orig/sdl12-compat-release-1.2.52/src/SDL12_compat.c 2022-03-03 06:56:56.000000000 -0800
+++ ./src/sdl12-compat-release-1.2.52/src/SDL12_compat.c        2022-05-06 13:15:12.647937592 -0700
@@ -6220,6 +6220,16 @@
     SDL_SysWMinfo info20;

     if (info12->version.major > 1) {
+        if (info12->version.major == 2) {
+#if defined(SDL_VIDEO_DRIVER_WINDOWS)
+            info12->window = (HWND)VideoWindow20;
+#elif defined(SDL_VIDEO_DRIVER_X11)
+            info12->info.x11.gfxdisplay = (Display *)VideoWindow20;
+#else
+            info12->data = (void *)VideoWindow20;
+#endif
+            return 1;
+        }
         SDL20_SetError("Requested version is unsupported");
         return 0;  /* some programs only test against 0, not -1 */
     } else if (!SupportSysWM) {
```
This facilitates SDL1.2 application to be used with SDL2 loadable plugins (DLL/lib.so/dylib) that can render into main window. In an ideal world that said SDL1.2 application should have been ported to SDL2 to be able to use SDL2 plugins. Unfortunately, this isn't always the case. Plumbing existing SDL1.2 SDL_GetWMInfo() to allow retrieval of SDL_Window enables that said SDL1.2 application to use SDL2 plugins with the least effort.

**Comment by slouken** [comment]
What if instead we define a structure SDL_SysWMinfo2 that has version and void* data and we fill that in instead of using the `#if defined()` hackery?

**Comment by kjliew** [comment]
That's perfectly fine, too.

**Comment by icculus** [comment]
Yeah, agree with @slouken here. I'll wire that up in the morning.

**Comment by kjliew** [comment]
A little background information, I have been trying to make SDL1.2 and SDL2 inter-operability through foreign window conversion in SDL2 using SDL_CreateWindowFrom() with a native window handle coming from SDL1.2 SDL_SysWMInfo. It was a bit of a hackery but worked quite well in Windows 10/11 and macOS. The later required a simple patch for the last official SDL 1.2.15 to have `info->nsWindowPtr` in SDL_SysWMInfo. The code was already there but commented out. For modern Linux, it worked within the entire runtime but SEGFAULT at `SDL_Quit()/SDL_QuitSubsystem()` in the graceful exit path of SDL1.2 application. This only applied when foreign window conversion ever took place during the runtime, otherwise the calls ended normally. An ugly workaround is possible to track foreign window conversion and skip `SDL_Quit()/SDL_QuitSubsystem()` and depends on the system garbage collector to deal with the leaks.

The proposed **sdl12-compat patch by retrieving SDL_Window** solved the issue on modern Linux without the ugly workaround. However, the same code failed on Windows 10/11 and macOS. I will see if I am able to produce simple test cases for the failures. I guess there is still work to be done for sdl12-compat to be truly the drop-in replacement for SDL1.2.

I do realize that Windows10/11 and macOS impose stricter restriction on threads and rendering context. Modern Linux is more relaxed in such matter. It is worth to consider this use case as the goal of SDL_Window retrieval such that the same thread context obtaining SDL_Window can pass it along into SDL2 and remains valid for rendering within the same thread context.

Thank you for looking into this.

**Comment by icculus** [comment]
Sat down to knock this out in five minutes and ended up taking an hour, but this is finally done. It exposes all SDL2 SysWM info instead of just the window, and there's a little test program to see how to use it correctly.

**Comment by kjliew** [comment]
@icculus @slouken Sorry to get back late on this. It seems that you misunderstood the requirement. What is needed the the real **`'SDL_Window'`** from SDL2 behind the scene, not the respective platform specific native window implementation. Commit  https://github.com/libsdl-org/sdl12-compat/commit/b13166f31a1d1b315744e6cc45901173d99590c7 implementation seems to be redundant and repetitive of what's already there from SDL 1.2 version of SDL_GetWMInfo().

Please re-open the issue for tracking purpose.

**Comment by kjliew** [comment]
Thanks for reopening the bug. The goal behind retrieving the real **`'SDL_Window'`** is to give SDL_Window directly to SDL2 plugins saving the plugins from doing foreign window conversion using `SDL_CreateWindowFrom()`. This is doable with SDL12-compat for having SDL2 behind the scene. I provided patch doing exactly this as **`'VideoWindow20'`** returned in place of native window handle.

**Comment by icculus** [comment]
Okay, I left the other stuff, for people that want the low-level details but don't want to talk to SDL2 directly, but also added an sdl2_window field, which contains the SDL2 `SDL_Window *`, which should solve your need, too.

Note that SDL 1.2 allows you to call this function before SDL_SetVideoMode(), in case you want the X11 display but not a specific window or whatever...to accommodate this, sdl12-compat will make a temporary window, call SDL2, and then destroy the window. In this case, sdl2_window in the results will be NULL (as VideoWindow20 will be NULL)...so plan accordingly.

**Comment by kjliew** [comment]
@icculus @slouken I really hope that you would agree to remove this big block of redundancy and just take my patch for simplicity. No one is going to write new codes based on SDL1.2 and the low-level details are already covered by the original 1.2 `SDL_GetWMInfo()`. The intuitiveness of `version.major` simplifies reusing existing SDL1.2 codes, `version.major == 1` for 100% SDL1.2 compatible `SDL_GetWMInfo()` and `version.major == 2` for real **`'SDL_Window'`** in place of native window.

This big block of redundancy presents much larger attack surface compared to the proposed simple patch. Isn't this something that many would have cared for today's code review? And, there is **no less** of `#if defined()` hackery in this redundant implementation.

**Comment by icculus** [comment]
I think what's there is fine and we'll all survive this level of, um, attack surface.

**Comment by kjliew** [comment]
> I think what's there is fine and we'll all survive this level of, um, attack surface.

I would disagree with you in the merits of code quality. You could have done an implementation with SDL_SysWMInfo2 with just the real **`'SDL_Window'`** as what I supposed @slouken had in mind and it should be fine. SDL12-compat is a compatibility layer for existing SDL1.2 apps, it is not for new codes. The excessive exposures of SDL2 low-level details beyond the original 1.2 SDL_GetWMInfo() is overly intrusive and unnecessary.

**Comment by slouken** [comment]
@kjliew, your patch caused an ABI change (converting int to void*), so I added a new field that you can use with sdl12-compat, implemented in https://github.com/libsdl-org/sdl12-compat/commit/0708d1e9a774fc2dca04af9805e660b1e53ebc24.

**Comment by kjliew** [comment]
@slouken Yes, converting `int` to `void*` caused ABI change, but only for the last #else case which is for nobody except macOS, but in SDL1.2 MacOS never had `SDL_GetWMInfo()`. Adding a new field caused ABI change for **ALL including WIN32 and X11** which are indeed the focus of SDL12-compat as direct replacement.

**Comment by kjliew** [comment]
Please re-open the bug for tracking purpose. @slouken last commit in https://github.com/libsdl-org/sdl12-compat/commit/0708d1e9a774fc2dca04af9805e660b1e53ebc24 had indeed broken ABI on WIN32 and Linux.
```
| sizeof() | Linux | WIN32 |
| Before   | 64    | 24    |
| After    | 72    | 32    |
```

**Comment by slouken** [comment]
We've added a new function for you in https://github.com/libsdl-org/sdl12-compat/commit/e7cf61ec93f0968dc94ae48c42181b057e74eabf

**Comment by kjliew** [comment]
@slouken So then any recompiled SDL1.2 apps cannot go back to real SDL1.2 when the new function is linked. Compared to the rejected patch, the recompiled SDL1.2 apps may fail but can retry with `wmi.version = 1` as **simple fallback**.

Anyway, I got to say **this is a very poor decision** not to take the patch, something that was already well thought out. Only if you guys could convince me that taking a new function is better. A bluntly disagreement without reasons is a disgrace.

**Comment by slouken** [comment]
The whole point to this function is to do SDL 1.2 <-> SDL 2.0 interop, so a new function makes sense here given that the expected use case is SDL 1.2 on 2.0. If you need fallback behavior, you are welcome to use `SDL_GL_GetProcAddress()` to retrieve the function pointer, and that will give the correct result on old and new libraries.

I know you are in love with your approach, but we reviewed it and decided not to overload existing SDL 1.2 behavior for this.

**Comment by kjliew** [comment]
If you guys reviewed it, then please list the reasons why overloading with `wmi.version == 2` is disastrous for existing SDL1.2 apps. This would make things look better on your side when any GitHub visitors look at the offered patch and the alternative solution. Frankly, I am very opened to alternative solution if they match in quality and simplicity. I am sorry to say that rejecting offered patch with existing alternative is indeed laughable, anyway.😜
