### ISSUE TITLE
Library install_name is wrong on macOS

### ISSUE THREAD

**Issue by jmroot** [libsdl-org/sdl12-compat#194]
The install_name is set to just `libSDL-1.2.0.dylib` (should be either the full installation path, or relative to `@something`.) Removing this line from `CMakeLists.txt` seems to fix it:
```
set_target_properties(SDL PROPERTIES INSTALL_NAME_DIR "")
```
Not quite sure why that is being done in the first place, but maybe there's a good reason?

**Comment by icculus** [comment]
> Not quite sure why that is being done in the first place, but maybe there's a good reason?

There might be, but I can't remember what at this point. I'll look into why (and possibly just remove the line).

**Comment by icculus** [comment]
Apparently I added this to shut off a cmake warning in 87433054970f14660d8713e1352b448817905391, and @sezero noted it didn't help, so I'll just back it out.
