### ISSUE TITLE
Scancodes are different between 1.2 and 2.0

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/sdl12-compat#20]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** unspecified
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2020-12-23 02:10:12 +0000, Malte Kießling wrote:

> So, the good old sdl 1.2 documentation states that scancodes are "best left alone". 
> 
> Turns out that people didn't care. There is the issue now that dosbox (to give an example) is somewhat activly using scancodes (dosbox/src/gui_sdl_mapper.cpp:421; function called GetKeyCode). The bounds-checking is also only an assert, so this is a guaranteed crash. 
> 
> I have "fixed" this by permanently setting the scancode of the key event to zero. I have no idea if that is an actual fix - who knows what else depends on the scancodes. Emulating old behaviour here is probalby preferable.

**Comment by sezero** [comment]
Fixed as of commit 53bd8b5f9f
