### ISSUE TITLE
Add a script to bump the version number...

### ISSUE THREAD

**Issue by icculus** [libsdl-org/sdl12-compat#205]
As both @sezero and myself had a lot of trouble updating the version number  :)  , maybe we should have a perl script or something that knows all the places to update, so it's always right.

**Comment by slouken** [comment]
Yes please. And while you're at it, do you want to add it for SDL and SDL_* libraries? @smcv did a great job documenting all the places that need to be changed in release_checklist.md

**Comment by icculus** [comment]
>  release_checklist.md

Ooh, I didn't see this before! I'll take a stab at this for sdl12-compat and open an SDL issue so I don't forget to manage it over there, too.
