### ISSUE TITLE
Any plans to support SDL2 dynapi solution to SDL12-compat

### ISSUE THREAD

**Issue by oiaohm** [libsdl-org/sdl12-compat#206]
https://github.com/libsdl-org/SDL/blob/main/docs/README-dynapi.md

The dynapi item is useful for cases that applications static link in the SDL items so they can be updated in future.

Yes static linking modern SDL2 into application does not prevent replacement.   Of course SDL12-compat being able to static linked in with like SDL12_DYNAMIC_API to replace could be option.

They reasons why SDL2 get static linked into executable does not go away for SDL1.2 programs.   Of course static linked in with SDL1.2 is truly problem.

**Comment by icculus** [comment]
I think at this point, no one is really writing _new_ 1.2 programs, and old binaries can't benefit from it.

That being said: SDL 1.2 was LGPL'd, which means closed-sourced programs couldn't statically link it without violating the license, so in practice this isn't _that_ much of a problem, I hope.

**Comment by oiaohm** [comment]
Not quite that simple.   Being open source does not mean problem free.   LGPL of SDL 1.2 is against closed source usage this is true.

Having source code of program does not mean it will build with current versions of compilers.   So it could be a LGPL program that user runs into trouble where the new binary was static linked.

The trap here is developer/maintainer of a binary of an application licensed under LGPL can still decide to statc link SDL 1.2.   End users can have the source and find them in the case that due to the differences between the compiler the maintainer/developer users and the one they results in some game issue or game source will not build with the compiler they have without lots of work.  Yes changes in compilers over time coming more picky over issues so refusing to build code.

There is still a problem here.   Of course maybe the other option is put in documentation with SDL12-compat that dynamic linking is the supported use case.

**Comment by icculus** [comment]
I'm not unsympathetic to the concern, but I still don't think we'll be adding a dynapi to sdl12-compat.

**Comment by slouken** [comment]
From a practical standpoint, that ship has already sailed. Anyone who is going to statically link SDL 1.2 has already done so, and we can’t do anything about that.
