### ISSUE TITLE
[patch] SDL_GetWMInfo always returns -1, some applications only test against 0

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/sdl12-compat#21]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Let SDL_GetWMInfo return 0 "not implemented" for now. (compat.SDL_GetWMInfo.v1.patch, text/plain, 2020-12-23 15:06:31 +0000, 418 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4598)

**Reported in version:** unspecified
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2020-12-23 15:06:31 +0000, Malte Kießling wrote:

> Created attachment 4598
> Let SDL_GetWMInfo return 0 "not implemented" for now.
> 
> SDL_GetWMInfo is currently returning -1. Documentation states this means the struct is not filled. 
> 
> Dosbox and some other places (http://sdl.beuc.net/sdl.wiki/SDL_GetWMInfo) however do
> 
> if (SDL_GetWMInfo(&info))
> 
> So correct behavior on the compat layer side still breaks stuff :( 
> I suggest always returning 0 as long as no wrapper is constructed. As long as the return value is somewhat managed, i think this would increase compatibility. 
> 
> ~mkalte

**Comment by sezero** [comment]
Fixed by commit 6c180942bff
