### ISSUE TITLE
SDL_SetVideoMode with bpp=0 is incorrect

### ISSUE THREAD

**Issue by icculus** [libsdl-org/sdl12-compat#213]
> In sdl12-compat, if an app calls `SDL_SetVideoMode(w, h, 0, 0)`, we'll give them whatever the desktop mode is set to, which on this laptop, SDL2 is reporting it as 24-bit...but SDL 1.2 reports this as 32-bit on this machine. So we should probably do the same

_Originally posted by @icculus in https://github.com/libsdl-org/sdl12-compat/issues/182#issuecomment-1251050983_

**Comment by sezero** [comment]
Has SDL-1.2 ever supported / reported 8 bits?

**Comment by slouken** [comment]
Yes, in late 90's there were desktop configurations that didn't have truecolor at all.

**Comment by slouken** [comment]
No, I don't think so at this point.

**Comment by icculus** [comment]
(I could have sworn SDL2 didn't even support 8-bit displays, but regardless of that) there isn't any direct pixel access in sdl12-compat, since it either goes in renderer texture or uses OpenGL, and both will convert to whatever display depth.

Plus we aren't going to bother with palettes if we really _do_ ever see an 8-bit display.
