### ISSUE TITLE
pipewire support

### ISSUE THREAD

**Issue by eNTi** [libsdl-org/sdl12-compat#214]
Since I'm currently trying to play "Enemy Territory: Quake Wars", I've stumbled upon another issue: My sound system. I'm using pipewire but can't seem to get it to work with sdl12-compat. Should there be support or could you add support for that. Is there any practical workaround? The game itself supports oss, alsa and openal. So far I couldn't get dmix to work with the game so it either blocks the device or can't because it's already in use.

**Comment by icculus** [comment]
The latest SDL2 supports pipewire, so if the game uses SDL 1.2 audio, sdl12-compat can transparently use pipewire already.

But we can't do much if the game doesn't support SDL audio.

Maybe OpenAL-Soft might support it...?
