### ISSUE TITLE
macOS dylib doesn't explicitly load SDL 2.0 dylib, causing dylibbundler failures

### ISSUE THREAD

**Issue by Kreeblah** [libsdl-org/sdl12-compat#217]
I noticed when building [a project](https://github.com/Kreeblah/MazeOfGalious) against sdl12-compat instead of SDL 1.2 that it failed to run, stating that it couldn't find SDL 2.0.

After some investigation, I found that the step that causes it to fail to load is when [dylibbundler](https://github.com/auriamg/macdylibbundler) is run against it, which packs dependent shared libraries into a given app bundle, and rewrites their paths to create a self-contained bundle for distribution.  The reason it's failing is because it's using `otool -l` to look through each library to determine where there are `LC_LOAD_DYLIB` calls, and includes those, and the build process here doesn't link SDL 2.0 that way.

I thought this would be as easy as adding a `target_link_libraries(SDL PRIVATE ${SDL2_LIBRARIES})` to `CMakeFiles.txt` around line 83, but that seems to add `-framework -lCocoa` as well (which obviously doesn't exist as a framework).  I'm not sure where that `-l` prefix is coming from on the Cocoa framework name.

Hard-coding my SDL 2.0 library paths and the literal string `-framework Cocoa` using `target_link_libraries` statements did let it build, and I was able to verify that `dylibbundler` works with the resulting dylib, so linking the library seems to be a solution.  I'm just not quite sure where CMake is getting that `-l` prefix from on the Cocoa framework.

Is there any chance this could be looked at?

**Comment by sezero** [comment]
You really shouldn't link to SDL2: sdl12-compat dlopen's it at runtime
and scans its presence at multiple locations:
https://github.com/libsdl-org/sdl12-compat/blob/main/src/SDL12_compat.c#L1081-L1133

Where do you put your SDL2 dylib/framework along with your own binary?

**Comment by Kreeblah** [comment]
I was wondering how it found the SDL 2.0 dylib.  That explains it.  I guess I'll need to figure out another solution here, then, if that's not recommended.

The ones I've been using are the ones built by Homebrew, and I'm on an M1 Mac, so they're in `/opt/homebrew/opt/sdl2/lib/` (`/opt/homebrew/opt/sdl2/` being a directory that gets symlinked to the directory where the current version is installed).  The `sdl12-compat` dylib ends up in `/opt/homebrew/opt/sdl12-compat/lib/`.

As for building that application, other than the `dylibbundler` step, it doesn't touch library locations.  So, when removing that from the build process, the binary uses the ones from wherever they are in the filesystem.

**Comment by Kreeblah** [comment]
Having looked over the code there for how sdl12-compat finds SDL 2.0 libraries (the comments were especially helpful), I tried copying the SDL 2.0 dylib from my directory into the app bundle alongside the sdl12-compat dylib unmodified, and that worked, so I guess I'll go that route.

I did [have to do more string munging in my cmake script](https://github.com/Kreeblah/MazeOfGalious/blob/main/CMakeLists.txt#L102-L111) than I'd have liked to get the path to the SDL 2.0 dylib I needed, but I at least have something working.

I'm not sure whether there's anything that anybody from the project here has thoughts about for making this use case more straightforward, so I'll leave this open just in case, but obviously it can be closed if it's out of scope.

**Comment by sezero** [comment]
One thing we need to know is the exact name of the SDL2 dylib library built
and installed by homebrew. `ls -l /opt/homebrew/opt/sdl2/lib/` output should
do fine.

**Comment by icculus** [comment]
This sounds like it has a solution, but I just wanted to add, we _can't_ link sdl12-compat directly to SDL2, because they have a lot of the same function names, but they aren't interchangeable, so loading the dylib at runtime after everything has been resolved by the dynamic linker is extremely crucial to this whole thing working.

**Comment by sezero** [comment]
> One thing we need to know is the exact name of the SDL2 dylib library built and installed by homebrew. `ls -l /opt/homebrew/opt/sdl2/lib/` output should do fine.

@icculus: I _think_ we can close this. But I asked the question above, because, as far as I can see, the autotools builds of SDL2 output `libSDL2-2.0.0.dylib` and we do look for it, but the cmake builds output `libSDL2-2.0.dylib` instead which don't look for - notice the lack of the last `.0` part in the name: what a mess. We should do something about it?

CC: @slouken and @madebr for the atotools / cmake name mess.

**Comment by Kreeblah** [comment]
Ah, now I see what you were looking for.  Homebrew uses the autotools build process for its binaries, so it distributes `libSDL2-2.0.0.dylib`:

```
$ ls -l /opt/homebrew/opt/sdl2/lib/
total 8096
drwxr-xr-x  3 kreeblah  admin       96 Aug 19 08:46 cmake/
-rw-r--r--  1 kreeblah  admin  1446096 Aug 20 20:45 libSDL2-2.0.0.dylib
-r--r--r--  1 kreeblah  admin  2425376 Aug 19 08:46 libSDL2.a
lrwxr-xr-x  1 kreeblah  admin       19 Aug 19 08:46 libSDL2.dylib@ -> libSDL2-2.0.0.dylib
-r--r--r--  1 kreeblah  admin   258984 Aug 19 08:46 libSDL2_test.a
-r--r--r--  1 kreeblah  admin      736 Aug 19 08:46 libSDL2main.a
drwxr-xr-x  3 kreeblah  admin       96 Aug 20 20:45 pkgconfig/```

**Comment by madebr** [comment]
>  the autotools builds of SDL2 output `libSDL2-2.0.0.dylib` and we do look for it, but the cmake builds output `libSDL2-2.0.dylib` instead which don't look for - notice the lack of the last `.0` part in the name: what a mess. We should do something about it?


SDL2's cmake script uses [`LT_RELEASE`](https://github.com/libsdl-org/SDL/blob/34f928abb77220c51f3100cf4539a356de9c9a29/CMakeLists.txt#L115) to [set the name of the output library](https://github.com/libsdl-org/SDL/blob/34f928abb77220c51f3100cf4539a356de9c9a29/CMakeLists.txt#L3081-L3083).
So only `libSDL2-2.0.dylib` is created + a `libSDL2.dylib` at install time.

I think, by doing
```cmake
set_target_properties(SDL2 PROPERTIES SOVERSION 0)
```
we can create `libSDL2-2.0.0.dylib` instead.
`libSDL2-2.0.dylib` should still be created as a symlink to `libSDL2-2.0.0.dylib` (at install time).

But somebody with an apple, please test this.

**Comment by sezero** [comment]
> I think, by doing
> 
> ```cmake
> set_target_properties(SDL2 PROPERTIES SOVERSION 0)
> ```
> 
> we can create `libSDL2-2.0.0.dylib` instead. `libSDL2-2.0.dylib` should still be created as a symlink to `libSDL2-2.0.0.dylib` (at install time).

Like this? If not, tell me so I can do a quick cross-build test on my linux.
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index c5ffc40..c7746e8 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -3080,6 +3080,7 @@ if(SDL_SHARED)
   if(APPLE)
     set_target_properties(SDL2 PROPERTIES
       MACOSX_RPATH 1
+      SOVERSION 0
       OUTPUT_NAME "SDL2-${LT_RELEASE}")
   elseif(UNIX AND NOT ANDROID)
     set_target_properties(SDL2 PROPERTIES
```

**Comment by sezero** [comment]
@icculus: Do we want something like the following here?
```diff
diff --git a/src/SDL12_compat.c b/src/SDL12_compat.c
index 18130aa..d1b69fa 100644
--- a/src/SDL12_compat.c
+++ b/src/SDL12_compat.c
@@ -1082,6 +1082,8 @@ static char loaderror[256];
     #include <pwd.h>
     #include <unistd.h>
     #define SDL20_LIBNAME "libSDL2-2.0.0.dylib"
+    /* SDL2 cmake'ry is (was?) messy: */
+    #define SDL20_LIBNAME2 "libSDL2-2.0.dylib"
     #define SDL20_FRAMEWORK "SDL2.framework/Versions/A/SDL2"
     #define SDL20_REQUIRED_VER SDL_VERSIONNUM(2,0,7)
     #define strcpy_fn  strcpy
@@ -1093,12 +1095,15 @@ static char loaderror[256];
         /* I don't know if this is the _right_ order to try, but this seems reasonable */
         static const char * const dylib_locations[] = {
             "@loader_path/" SDL20_LIBNAME, /* MyApp.app/Contents/MacOS/libSDL2-2.0.0.dylib */
+            "@loader_path/" SDL20_LIBNAME2, /* MyApp.app/Contents/MacOS/libSDL2-2.0.dylib */
             "@loader_path/../Frameworks/" SDL20_FRAMEWORK, /* MyApp.app/Contents/Frameworks/SDL2.framework */
             "@executable_path/" SDL20_LIBNAME, /* MyApp.app/Contents/MacOS/libSDL2-2.0.0.dylib */
+            "@executable_path/" SDL20_LIBNAME2, /* MyApp.app/Contents/MacOS/libSDL2-2.0.dylib */
             "@executable_path/../Frameworks/" SDL20_FRAMEWORK, /* MyApp.app/Contents/Frameworks/SDL2.framework */
             NULL,  /* /Users/username/Library/Frameworks/SDL2.framework */
             "/Library/Frameworks" SDL20_FRAMEWORK, /* /Library/Frameworks/SDL2.framework */
-            SDL20_LIBNAME  /* oh well, anywhere the system can see the .dylib (/usr/local/lib or whatever) */
+            SDL20_LIBNAME, /* oh well, anywhere the system can see the .dylib (/usr/local/lib or whatever) */
+            SDL20_LIBNAME2
         };
 
         int i;
```

**Comment by madebr** [comment]
> Like this? If not, tell me so I can do a quick cross-build test on my linux.
> 
> ```diff
> diff --git a/CMakeLists.txt b/CMakeLists.txt
> index c5ffc40..c7746e8 100644
> --- a/CMakeLists.txt
> +++ b/CMakeLists.txt
> @@ -3080,6 +3080,7 @@ if(SDL_SHARED)
>    if(APPLE)
>      set_target_properties(SDL2 PROPERTIES
>        MACOSX_RPATH 1
> +      SOVERSION 0
>        OUTPUT_NAME "SDL2-${LT_RELEASE}")
>    elseif(UNIX AND NOT ANDROID)
>      set_target_properties(SDL2 PROPERTIES
> ```

100%. When it ends up being correct, please add a comment why we're doing this so we can remove it for SDL3.

**Comment by icculus** [comment]
@sezero apply that sdl12-compat patch, please!

**Comment by sezero** [comment]
> @sezero apply that sdl12-compat patch, please!

Done: https://github.com/libsdl-org/sdl12-compat/commit/bf91f6aad1fce952a3c11dc6ace155a2d1f428b8

**Comment by sezero** [comment]
> 100%. When it ends up being correct, please add a comment why we're doing this so we can remove it for SDL3.

Done: https://github.com/libsdl-org/SDL/commit/f6c9b06562009d184d953d6207f4bcd7c659c989

@icculus: This can be closed?
