### ISSUE TITLE
[patch] Initial Dosbox compatibility

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/sdl12-compat#22]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Dosbox compatibility (compat.dosbox.v1.patch, text/plain, 2020-12-23 15:41:17 +0000, 1686 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4599)

**Reported in version:** unspecified
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2020-12-23 15:41:17 +0000, Malte Kießling wrote:

> Created attachment 4599
> Dosbox compatibility
> 
> Im throwing everything in this one as im too stupid to base patches on each other. 
> 
> This patch does three things 
>   * A messy solution (set scancode to 0) for bug 5412
>   * Same change as in bug 5413 letting SDL_GetHWInfo return 0 instead of -1
> 
> The thrid thing comes from something weird dosbox does: 
> To check for the presence of double buffering  they have two ways: they either check via SDL_DOUBLEBUF or they check the screen surface via SDL_MUSTLOCK. 
> 
> Currently, compat sets DOUBLEBUF but not HWSURFACE, thus causing dosbox to draw into one surface (cuase doublebuf is present!) but then not upating stuff properly (cause MUSTLOCK returns 0).
> 
> So the thrid thing this patch does is set SDL_HWSURFACE next to SDL_DOUBLEBUF for VideoSurface12.
> 
> That was a little weird to figure out. 
> 
> Happy holidays and whatnot to everyone :D
> 
> ~mkalte

**Comment by sezero** [comment]
GetWMInfo part is fixed as of commit 6c180942bff

**Comment by mkalte666** [comment]
Do you want me to rebase my patch and create a pull request, or are you fine with just the info?

**Comment by sezero** [comment]
> Do you want me to rebase my patch and create a pull request, or are you fine with just the info?

IMO, the info should be enough.  I'd like a review of it by @icculus first, though.

**Comment by icculus** [comment]
These changes look good to me.

**Comment by sezero** [comment]
Fixed as commits 37c12055390f and 53bd8b5f9f

**Comment by slouken** [comment]
We'll probably need to do real scancode conversion at some point, but this is fine for now.
