### ISSUE TITLE
DOSBox SVN suffers low graphics performance on macOS with `output=opengl`

### ISSUE THREAD

**Issue by kjliew** [libsdl-org/sdl12-compat#220]
Homebrew had replaced `sdl` with `sdl12-compat`. Vanilla DOSBox SVN r4481 with `output=opengl` suffers low graphics performance. Tested using MDKDOS and PCPBENCH DOS4GW SVGA benchmarks. The drop in performance is extremely significant that OpenGL seemed `Unaccelerated` though GL strings returned `"Apple M1 OpenGL 2.1 Metal - 76.3"`

On modern Linux, `sdl12-compat` is superb for DOSBox SVN r4481.

MSYS2/mingw-w64 does not seem to endorse `sdl12-compat`. So this is not tested on Windows 10/11.

Apple M1 macOS Monterey 12.6
SDL2-2.24.0
sdl12-compat 1.2.56

**Comment by kjliew** [comment]
I figured it out that this is not `sdl12-compat` to blame, but due to DOSBox SVN handling of `SDL_ACTIVEEVENT` and changing priority on losing focus. The drop in performance reproduced exactly on Windows 11.

On Linux, DOSBox SVN has hackery that filtered out unwanted `SDL_ACTIVEEVENT`. The hackery was tagged with comment that this was an SDL1.2 bug on X11 but the same hackery did not fix the problem on Windows 11/macOS. There is a more elegant & easy way to deal with unwanted `SDL_ACTIVEEVENT` that solves this issue on Windows/macOS.

@icculus Since you had marked this issue with a milestone, perhaps you found other related issues that you planned to fix. Otherwise, feel free to close it as I think the ball should be in the court of DOSBox SVN.

**Comment by icculus** [comment]
Cool, I hadn't gotten around to debugging this yet, so I appreciate you having done this deeper research!

I'll close this issue now.
