### ISSUE TITLE
Do'SSi Zo'la: some UI elements disappear

### ISSUE THREAD

**Issue by smcv** [libsdl-org/sdl12-compat#233]
Prerequisites:

* Debian testing (Debian 12 alpha)
* Video: GNOME 43 in Wayland mode (with Mesa 22.2.0 on AMD Vega, if it matters)
* Audio: Pipewire 0.3.59, with `pipewire-pulse` emulating PulseAudio
* `apt install dossizola` (Debian package version `1.0-12`; it's a digital board game)
* Some relevant libraries:
    * `libsdl1.2-compat` commit eba13ef, locally-built
    * `libsdl2-2.0-0` version `2.24.1+dfsg-1`

To reproduce:

* `LD_LIBRARY_PATH=.../sdl12-compat/_build dossizola`
* Start
* Click a position in the grid for player 1 (green)
* Click a position in the grid for player 2 (red)
* Gameplay alternates between players: click an adjacent square to move to it, then click a square not containing the other player to delete from the board
* After a few turns, press Esc to exit

Expected result: Both players are visible at all times, with the active player animated and the inactive player standing still. All UI text is visible, including "Exit Now : [ No ] [ Yes ]" in the exit confirmation prompt.

Actual result: The active player is visible and animated. The inactive player is invisible. The prompt to move or fire appears for player 1, but not for player 2. When I press Esc to exit, I see "Exit Now : [ Yes ]", with the "No" button invisible.

**Comment by icculus** [comment]
This is something wrong with SDL_SetAlpha; if I comment it out, the game renders (with some things blending incorrectly, of course) without any pieces suddenly vanishing.

**Comment by icculus** [comment]
This is failing because eventually we end up in SDL2's SDL_BlitSurface (SDL_UpperBlit), and when trying to figure out _what_ to do with these surfaces, we land in this switch statement in `SDL_CalculateBlit1` ...

https://github.com/libsdl-org/SDL/blob/237348c772b4ff0e758ace83f471dbf8570535e2/src/video/SDL_blit_1.c#L529-L544

...and `surface->map->info.flags` is `SDL_COPY_COLORKEY | SDL_COPY_BLEND`, which this switch statement doesn't handle, so we get a NULL and it fails all the way back out of SDL_BlitSurface without blitting anything.

I'm not really sure how to deal with this yet.

**Comment by icculus** [comment]
Here's the SDL2 fix. I think this is probably more correct than working around this in sdl12-compat, and for something as obscure as this game, I'm willing to leave it broken for people that aren't on the upcoming SDL 2.28.0 release.

```diff
diff --git a/src/video/SDL_blit_1.c b/src/video/SDL_blit_1.c
index ba56979bf..f7c5b8099 100644
--- a/src/video/SDL_blit_1.c
+++ b/src/video/SDL_blit_1.c
@@ -533,6 +533,9 @@ SDL_CalculateBlit1(SDL_Surface *surface)
     case SDL_COPY_COLORKEY:
         return one_blitkey[which];
 
+    case SDL_COPY_COLORKEY | SDL_COPY_BLEND:  /* this is not super-robust but handles a specific case we found sdl12-compat. */
+        return (surface->map->info.a == 255) ? one_blitkey[which] : (SDL_BlitFunc)NULL;
+
```

@slouken, any objection to me applying this to SDL2/SDL3?

**Comment by icculus** [comment]
Okay, we're good here. Closing!
