### ISSUE TITLE
Gravity Wars: messed up colour palette

### ISSUE THREAD

**Issue by smcv** [libsdl-org/sdl12-compat#238]
Prerequisites:

* Debian testing (Debian 12 alpha)
* Video: GNOME 43 in Wayland mode (with Mesa 22.2.0 on AMD Vega, if it matters)
* Audio: Pipewire 0.3.59, with `pipewire-pulse` emulating PulseAudio
* `apt install gravitywars` (Debian package version `1.102-35`)
* Some relevant libraries:
    * `libsdl1.2-compat` either 1.2.58-1 (packaged in Debian experimental) or commit eba13ef (locally built)
    * `libsdl2-2.0-0` version `2.24.1+dfsg-1`

To reproduce:

* `gravitywars`
* `LD_LIBRARY_PATH=.../sdl12-compat/_build ld.so /usr/games/gravitywars`
* `SDL_VIDEODRIVER=wayland LD_LIBRARY_PATH=.../sdl12-compat/_build ld.so /usr/games/gravitywars`

Expected result: all work, except for their access to high scores not working because this use of `ld.so` disables setgid

~~Actual result: a segfault with Wayland~~ ­— this was caused by setgid games, similar to https://github.com/libsdl-org/sdl12-compat/issues/247#issuecomment-1276887769

Actual result: with sdl12-compat, either native Wayland or X11, the colour palette is wrong. Classic SDL 1.2:

![gravitywars-good](https://user-images.githubusercontent.com/1561141/195583861-26244590-e993-405e-b7f4-63f295bc6ff7.png)

sdl12-compat:

![gravitywars-bad](https://user-images.githubusercontent.com/1561141/195583858-2ead883e-5f81-4573-95e3-96d8c7a9fe65.png)

**Comment by icculus** [comment]
Same deal about LD_LIBRARY_PATH and setgid binaries, but the colors are wrong on this game once you get past that.

**Comment by icculus** [comment]
(if you remove the setgid bit, it'll fail to write the highschool and terminate the process at the end of the first round, but that's not an sdl12-compat issue.)

**Comment by icculus** [comment]
Also broken by 9da8808c03e80a228ee66a714091249f331ebcd7.

**Comment by sezero** [comment]
This shouldn't be fixed by 35488c6, it should be #248 instead.

**Comment by sezero** [comment]
> This shouldn't be fixed by [35488c6](https://github.com/libsdl-org/sdl12-compat/commit/35488c6894cb55ae4019392022c418f54dc3eb42), it should be #248 instead.

Ignore noise - wrong ticket.

**Comment by smcv** [comment]
Confirmed fixed as of https://github.com/libsdl-org/sdl12-compat/commit/67f8b3a85b782eefb4db90f34d5b0742ef2cb5fc (1.2.58 + 29 commits)
