### ISSUE TITLE
Heroes / Wayland: Failed to open visual: No available video device

### ISSUE THREAD

**Issue by smcv** [libsdl-org/sdl12-compat#240]
Prerequisites:

* Debian testing (Debian 12 alpha)
* Video: GNOME 43 in Wayland mode (with Mesa 22.2.0 on AMD Vega, if it matters)
* Audio: Pipewire 0.3.59, with `pipewire-pulse` emulating PulseAudio
* `apt install heroes` (Debian package version `0.21-18`)
* Some relevant libraries:
    * `libsdl1.2-compat` either 1.2.58-1 (packaged in Debian experimental) or commit 63e4393 (locally built)
    * `libsdl2-2.0-0` version `2.24.1+dfsg-1`

To reproduce:

* `heroes`
* `LD_LIBRARY_PATH=.../sdl12-compat/_build heroes`
* `SDL_VIDEODRIVER=wayland LD_LIBRARY_PATH=.../sdl12-compat/_build heroes`

Expected result: all work

Actual result: with sdl12-compat *and* `SDL_VIDEODRIVER=wayland`, it fails during startup. Workaround: use X11.

```
heroes: No joystick found (run with `-J' to suppress this message).
heroes: Failed to open visual: No available video device
```

**Comment by icculus** [comment]
setgid issue.

**Comment by smcv** [comment]
Confirmed, same as https://github.com/libsdl-org/sdl12-compat/issues/247#issuecomment-1276887769
