### ISSUE TITLE
lbreakout2 / Wayland: No available video device

### ISSUE THREAD

**Issue by smcv** [libsdl-org/sdl12-compat#243]
Prerequisites:

* Debian testing (Debian 12 alpha)
* Video: GNOME 43 in Wayland mode (with Mesa 22.2.0 on AMD Vega, if it matters)
* Audio: Pipewire 0.3.59, with `pipewire-pulse` emulating PulseAudio
* `apt install lbreakout2` (Debian package version `2.6.5-2`)
* Some relevant libraries:
    * `libsdl1.2-compat` either 1.2.58-1 (packaged in Debian experimental) or commit 63e4393 (locally built)
    * `libsdl2-2.0-0` version `2.24.1+dfsg-1`

To reproduce:

* `lbreakout2`
* `LD_LIBRARY_PATH=.../sdl12-compat/_build lbreakout2`
* `SDL_VIDEODRIVER=wayland LD_LIBRARY_PATH=.../sdl12-compat/_build lbreakout2`

Expected result: all work

Actual result: with sdl12-compat *and* `SDL_VIDEODRIVER=wayland`, it fails during startup. Workaround: use X11.

```
LBreakout2 2.6.5
Copyright 2001-2011 Michael Speck
Published under GNU GPL
---
Looking up data in: /usr/share/games/lbreakout2
Looking up highscores in: /var/games
Looking up custom levels in: /home/desktop/.lgames/lbreakout2-levels
/home/desktop/.lgames/lbreakout2.conf: file not found
Fatal STK Error!
No available video device
```

**Comment by icculus** [comment]
setgid issue.

**Comment by smcv** [comment]
Confirmed, same as https://github.com/libsdl-org/sdl12-compat/issues/247#issuecomment-1276887769
