### ISSUE TITLE
lmarbles/ltris on Wayland: No available video device

### ISSUE THREAD

**Issue by smcv** [libsdl-org/sdl12-compat#245]
Prerequisites:

* Debian testing (Debian 12 alpha)
* Video: GNOME 43 in Wayland mode (with Mesa 22.2.0 on AMD Vega, if it matters)
* Audio: Pipewire 0.3.59, with `pipewire-pulse` emulating PulseAudio
* `apt install lmarbles` (Debian package version `1.0.8-0.2`)
* Some relevant libraries:
    * `libsdl1.2-compat` either 1.2.58-1 (packaged in Debian experimental) or commit 63e4393 (locally built)
    * `libsdl2-2.0-0` version `2.24.1+dfsg-1`

To reproduce:

* `lmarbles`
* `LD_LIBRARY_PATH=.../sdl12-compat/_build lmarbles`
* `SDL_VIDEODRIVER=wayland LD_LIBRARY_PATH=.../sdl12-compat/_build lmarbles`

Expected result: all work

Actual result: with sdl12-compat *and* `SDL_VIDEODRIVER=wayland`, it crashes with:

```
ERR: sdl_init: No available video device
```

**Comment by smcv** [comment]
Same with ltris 1.0.19-3+b1, by the same author.

**Comment by icculus** [comment]
setgid on both titles.

**Comment by smcv** [comment]
Confirmed, same as https://github.com/libsdl-org/sdl12-compat/issues/247#issuecomment-1276887769
