### ISSUE TITLE
meritous: Draws in monochrome

### ISSUE THREAD

**Issue by smcv** [libsdl-org/sdl12-compat#246]
Prerequisites:

* Debian testing (Debian 12 alpha)
* Video: GNOME 43 in Wayland mode (with Mesa 22.2.0 on AMD Vega, if it matters)
* Audio: Pipewire 0.3.59, with `pipewire-pulse` emulating PulseAudio
* `apt install meritous` (Debian package version `1.5-1.1`)
* Some relevant libraries:
    * `libsdl1.2-compat` either 1.2.58-1 (packaged in Debian experimental) or commit 63e4393 (locally built)
    * `libsdl2-2.0-0` version `2.24.1+dfsg-1`

To reproduce:

* `meritous`
* `LD_LIBRARY_PATH=.../sdl12-compat/_build meritous`
* `SDL_VIDEODRIVER=wayland LD_LIBRARY_PATH=.../sdl12-compat/_build meritous`

Expected result: all work

Actual result: with real SDL 1.2, the menu is in shades of cyan and initial gameplay is in shades of blue. With sdl12-compat (either X11 or Wayland), both are in shades of grey.

**Comment by icculus** [comment]
Likely broken by 9da8808c03e80a228ee66a714091249f331ebcd7, the same as #248.

**Comment by smcv** [comment]
Confirmed fixed as of https://github.com/libsdl-org/sdl12-compat/commit/67f8b3a85b782eefb4db90f34d5b0742ef2cb5fc (1.2.58 + 29 commits)
