### ISSUE TITLE
openjazz: Renders in monochrome

### ISSUE THREAD

**Issue by smcv** [libsdl-org/sdl12-compat#248]
Prerequisites:

* Debian testing (Debian 12 alpha)
* Video: GNOME 43 in Wayland mode (with Mesa 22.2.0 on AMD Vega, if it matters)
* Audio: Pipewire 0.3.59, with `pipewire-pulse` emulating PulseAudio
* `apt install openjazz game-data-packager`
* `game-data-packager -i jazz-jackrabbit` (installs a demo version of the required data)
* Some relevant libraries:
    * `libsdl1.2-compat` either 1.2.58-1 (packaged in Debian experimental) or commit 63e4393 (locally built)
    * `libsdl2-2.0-0` version `2.24.1+dfsg-1`

To reproduce:

* `OpenJazz /usr/share/games/jazz-jackrabbit-hh95`
* `LD_LIBRARY_PATH=.../sdl12-compat/_build OpenJazz /usr/share/games/jazz-jackrabbit-hh95`
* `SDL_VIDEODRIVER=wayland LD_LIBRARY_PATH=.../sdl12-compat/_build OpenJazz /usr/share/games/jazz-jackrabbit-hh95`

Expected result: all work

Actual result: real SDL 1.2 works as expected, sdl12-compat renders in monochrome similar to #246

**Comment by icculus** [comment]
This broke with 9da8808c03e80a228ee66a714091249f331ebcd7, so clearly my understanding of the SDL 1.2 palette management is not correct. I'll look into this further.

**Comment by sezero** [comment]
This one should be fixed by 35488c6 ?

Also: Did 35488c6 not bring back #216?

**Comment by icculus** [comment]
> Also: Did https://github.com/libsdl-org/sdl12-compat/commit/35488c6894cb55ae4019392022c418f54dc3eb42 not bring back https://github.com/libsdl-org/sdl12-compat/issues/216?

It did, I just hadn't reopened it yet.  :)

**Comment by smcv** [comment]
Confirmed fixed as of https://github.com/libsdl-org/sdl12-compat/commit/67f8b3a85b782eefb4db90f34d5b0742ef2cb5fc (1.2.58 + 29 commits)
