### ISSUE TITLE
Software renderer issues:

### ISSUE THREAD

**Issue by sezero** [libsdl-org/sdl12-compat#25]
When uhexen2 (http://uhexen2.sf.net/) is isrun in software renderer
mode, and the resoultion is not the desktop resolution:

- Windowed mode is OK, that much is fine.

- Alt-Enter toggling to fullscreen adjusts the drawable area, but
  the non-drawable area, i.e. the left and right sides of the screen
  are left not drawn, has desktop leftovers and flickers (e.g. with
  a 1024x768 game window, 1920x1080 desktop.)

- Alt-Enter back to windowed mode: The drawable area is shifted to
  right, making the game unplayable: See the attached screenshot.

The issues seem to be related to SDL_WINDOW_FULLSCREEN_DESKTOP:
Using SDL_WINDOW_FULLSCREEN makes the issues go away.

Should we check that the game window resolution matches the desktop
before deciding to use SDL_WINDOW_FULLSCREEN_DESKTOP?  Or a better
solution?
![sshot](https://user-images.githubusercontent.com/4222725/108607243-44d2f580-73d0-11eb-9c49-8ae3ddfe78a5.png)

**Comment by slouken** [comment]
I'd have to look closer at the code to see what's causing this, but the behavior I'd expect is:
* Fullscreen windows should use SDL_WINDOW_FULLSCREEN_DESKTOP
* If they don't fit the aspect ratio of the desktop, then there should be black bars as needed to cover area that isn't filled by the video surface
* The video surface probably shouldn't change, we should just use the renderer to change how it's displayed. I think we get most of this for free by using the renderer logical size API.

**Comment by sezero** [comment]
> I'd have to look closer at the code to see what's causing this, 

Looking forward to it.

**Comment by icculus** [comment]
The fix in https://github.com/libsdl-org/sdl12-compat/commit/df0382b7b8939d90d20b2c8640cb8273af5282b5 takes care of the issues when going fullscreen, but this doesn't fix the problem when alt-enter'ing back to windowed mode. I'll look at that tomorrow.

**Comment by icculus** [comment]
This was a fun bug, but now I can toggle both to and from fullscreen mode in uhexen2 without problems.

**Comment by sezero** [comment]
Thanks

**Comment by slouken** [comment]
Nice solution!
