### ISSUE TITLE
perl-SDL testsuite get stuck in SDL_FreeYUVOverlay() after SDL_LockMutex_REAL() since 1.2.56 (1.2.52 was OK)

### ISSUE THREAD

**Issue by soig** [libsdl-org/sdl12-compat#275]
It builds smoothly with 1.2.52 : See logs
https://pkgsubmit.mageia.org/autobuild/cauldron/x86_64/core/2022-08-19/perl-SDL-2.548.0-10.mga9.src.rpm/

But it but testsuite got stucks with 1.2.56 & 1.2.60 on both Fedora & Mageia distributions:
Here's the logs with 1.2.56: https://pkgsubmit.mageia.org/autobuild/cauldron/x86_64/core/2022-10-31/perl-SDL-2.548.0-10.mga9.src.rpm/)

Running it manually shows that it's stuck in SDL_FreeYUVOverlay().
I've attached the GDB backtraces for both Fedora & Mageia distributions..
[bt-mga.txt](https://github.com/libsdl-org/sdl12-compat/files/10032620/bt-mga.txt)
[bt-fc.txt](https://github.com/libsdl-org/sdl12-compat/files/10032619/bt-fc.txt)

So 1.2.56 broke down (as 1.2.54 was the same but a pre-version?).
Downgrading to 1.2.52 immediately fix (no more hang)

**How to reproduce:**
```
lftpget https://cpan.metacpan.org/authors/id/F/FR/FROGGS/SDL-2.548.tar.gz
tar xf SDL-2.548.tar.gz
cd SDL-2.548/
perl Build.PL 
./Build
# Then you can either run ./Build test or just run the offending test:
perl -Iblib/lib -Iblib/arch t/core_video.t 
# or just run it directly in gdb ("break SDL_FreeYUVOverlay" then "r"):
gdb -q --args perl -Iblib/lib -Iblib/arch t/core_video.t
```

It seems to hang right after playing with some mutex (using SDL_LockMutex_REAL())

**Comment by soig** [comment]
This might be the offending commit: https://github.com/libsdl-org/sdl12-compat/commit/184565a3ae07cbcc508d8427b51b5b5b3ca01f05

**Comment by slouken** [comment]
Can you attach the backtrace from all the threads in the process?

**Comment by slouken** [comment]
Oh yeah, that's clearly wrong.

Here, try this:
```diff
diff --git a/src/SDL12_compat.c b/src/SDL12_compat.c
index 6964e2b..fb657a6 100644
--- a/src/SDL12_compat.c
+++ b/src/SDL12_compat.c
@@ -7535,6 +7535,7 @@ SDL_FreeYUVOverlay(SDL12_Overlay *overlay12)
             if (overlay->overlay12 == overlay12) {
                 overlay->overlay12 = NULL;  /* don't try to draw this later. */
             }
+            overlay = overlay->next;
         }
 
         if (renderer) {
```

**Comment by soig** [comment]
That fixed it on the Mageia box

**Comment by slouken** [comment]
Great, thanks!

**Comment by icculus** [comment]
Good catch, Sam, thanks!
