### ISSUE TITLE
Error with new version of smpeg

### ISSUE THREAD

**Issue by Yuri-K7** [libsdl-org/sdl12-compat#276]
Not exactly sure if it's an issue from sdl12-compat or sdl_mixer or archlinux repos, but as it's caused by smpeg being updated from 0.4.5 to 2.0.0, I'm reporting here.

When running onscripter on archlinux from the aur, I got the following error :
>onscripter: error while loading shared libraries: libsmpeg-0.4.so.0: cannot open shared object file: No such file or directory

and it won't compile anymore...
>CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
>Please set them or make sure they are set and tested correctly in the CMake files:
>SMPEG_LIBRARY

**Comment by icculus** [comment]
This looks like it's looking for an older version of smpeg, which isn't installed, and not an sdl12-compat issue.
