### ISSUE TITLE
Mac version not trying to load SDL2.framework

### ISSUE THREAD

**Issue by sezero** [libsdl-org/sdl12-compat#28]
Mac version should first try loading `SDL2.framework/Versions/A/SDL2`
from `~/Library/Frameworks` and `/Library/Frameworks` folders (is the
order correct?), and then try `libSDL2-2.0.0.dylib` if the framework
fails.

**Comment by icculus** [comment]
I'm not sure we should check /Library/Frameworks; I think that's off-limits for end users in modern macOS, but I guess we could check ~/Library/Frameworks.

**Comment by sezero** [comment]
https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPFrameworks/Tasks/InstallingFrameworks.html
says `/System/Library/Frameworks` is verboten but `/Library/Frameworks` is the
usual place to install 3rd party frameworks. That page is last updated at  2013-09-17
(says on the page), is there a more up-to-date information somewhere?

**Comment by icculus** [comment]
Just checked on 10.14, and this is still correct. The root user (but not even users marked as Administrators) can write into /Library/Frameworks.

**Comment by sezero** [comment]
I pushed 6fcbc1639e385fdbfd7d9ee40415e1bd362ac668 for this, for now.

Tried uhexen2 with it: if the framework is under `~/Library/Frameworks`
or `/Library/Frameworks`, it runs fine. However, if loading SDL2 fails,
it does _not_ show the alert panel, only the OS error dialog because of
abort().  That's probably due to missing Cocoa initialization, which is
beyond me: Yours to fix.

Note:  It will try the first library it finds. Meaning: if the one it
finds has missing symbols or an old version, other paths aren't tried.

**Comment by sezero** [comment]
Noticed one thing with keys:  With SDL-1.2, I'd hit FN+<funckey> to use
the functions keys, e.g. FN+F3 to load a game, FN+F10 to quit the game.
With the compat-layer, FN+F3 is OK, but FN+F10 does something different,
I have to use <Option>+F10 for it.

**Comment by icculus** [comment]
> Noticed one thing with keys

Kicked this over to a new issue to look at later (it's kinda fun that GitHub lets one do that right from an individual comment!).

I'm going to poke at the Mac framework issues a bit more on my end.

**Comment by icculus** [comment]
I fixed the error dialog in #47, and I think the framework stuff is settled okay here, so I'm closing this. Please reopen if you think it needs more work, though, and I'll work on it more.

**Comment by icculus** [comment]
(Issue #40 still exists and continues this effort, though.)

**Comment by icculus** [comment]
okay, I went crazy here.
