### ISSUE TITLE
Plans for release 1.2.61?

### ISSUE THREAD

**Issue by hartwork** [libsdl-org/sdl12-compat#286]
Hi!

It will soon be five months since the latest release 1.2.60 and [there are fixes on `master` since then](https://github.com/libsdl-org/sdl12-compat/compare/release-1.2.60...main) that users will be happy about. Are there any plans for a release 1.2.61?

Thanks and best, Sebastian

**Comment by icculus** [comment]
Yeah, this has been pending...I'll see if I can get a release out this week, if possible!

**Comment by hartwork** [comment]
Cool! :+1:

**Comment by DominusExult** [comment]
Just to chime in, would it be possible to add a release dll for Windows next time?
I just had the discussion with someone and thought I could just point him here, let him grab the dll, then the SDL2 dll and he would be good :(

**Comment by icculus** [comment]
> Just to chime in, would it be possible to add a release dll for Windows next time?

CC @slouken: is this something we can reasonably do from the same place you generate SDL release binaries? I don't know if that's easy or complicated.

**Comment by slouken** [comment]
Possibly, I'll take a look. How do you currently create the release?

**Comment by icculus** [comment]
> How do you currently create the release?

I think we've just been tagging it in git and telling GitHub "this tag is the release's commit" and letting it build a tarball. I don't think we've done builds for any platform so far, just source code.

**Comment by slouken** [comment]
Yeah, let me know when you're getting close to release, and I'll set up a Windows DLL build here.

**Comment by icculus** [comment]
Okay, I'm going to tag a prerelease 1.2.62 today, which will become a 1.2.64 stable release about a week later.

@sezero, do you have anything you want to do before I set the prerelease tag?

**Comment by icculus** [comment]
Also CC @sulix, in case you have anything pending you want to get into this release.

**Comment by sezero** [comment]
> @sezero, do you have anything you want to do before I set the prerelease tag?

Not particularly.

Does #216 has a change of getting fixed before release?

**Comment by icculus** [comment]
> Does https://github.com/libsdl-org/sdl12-compat/issues/216 has a change of getting fixed before release?

It felt too risky, considering last time it broke dozens of games.

That fork of quake2 isn't popular, so it's not high-priority. We'll try to fix it for the next release.

**Comment by icculus** [comment]
Okay, 1.2.62 PRERELEASE is live: https://github.com/libsdl-org/sdl12-compat/releases/tag/prerelease-1.2.62

The git repo now reports itself as 1.2.63 and will bump to .64 for the official release. We'll let this marinate for a week or so before the release.

@slouken, you can add Windows DLLs to this [here](https://github.com/libsdl-org/sdl12-compat/releases/edit/prerelease-1.2.62) and look for the thing about attaching files at the bottom of that page, if you want to take a shot at building those.

**Comment by slouken** [comment]
Windows DLLs built and added to the release!

**Comment by sulix** [comment]
> Also CC @sulix, in case you have anything pending you want to get into this release.

Nothing on my end.

There was an audio regression on Uplink, but it turned out to be an sdl2-compat issue (https://github.com/libsdl-org/sdl2-compat/pull/75), and doesn't reproduce with sdl12-compat on top of real SDL2.

**Comment by icculus** [comment]
Last call on this, probably releasing 1.2.64 today if there are no objections.

**Comment by icculus** [comment]
Tagging release in 60 minutes.

**Comment by icculus** [comment]
![image](https://github.com/libsdl-org/sdl12-compat/assets/673562/c0a6bd9f-4bee-4479-ade9-39520a8b351c)

I see this is still running on Icculus Time.  :)

This is officially released!

https://github.com/libsdl-org/sdl12-compat/releases/tag/release-1.2.64

@slouken, feel free to build Windows .dlls if you want to [add them to the release](https://github.com/libsdl-org/sdl12-compat/releases/edit/release-1.2.64).

I have bumped revision control to 1.2.65, which will someday become a 1.2.66 prerelease and an official 1.2.68, if it works hard in school and eats its vegetables. But for now, this issue can be closed! Thanks everyone!

**Comment by icculus** [comment]
(Also, CC @Conan-Kudo, for pulling the new release into Fedora at his leisure.)

**Comment by hartwork** [comment]
Thanks for making this happen! :pray:

**Comment by slouken** [comment]
Windows binaries are up!
