### ISSUE TITLE
hhexen doesn't receive any events

### ISSUE THREAD

**Issue by sezero** [libsdl-org/sdl12-compat#29]
hhexen [1,2] doesn't receive any events: Putting debug prints in
I_StartTic (called from H2_GameLoop()'s while(1) loop), I can see
it does enter, but gets no events: https://github.com/sezero/hhexen/blob/master/sdl/i_sdlgl.c#L424

I have to `kill -9` it from another terminal window.  Don't know
whether this is hhexen's fault.

[1] https://github.com/sezero/hhexen
[2] https://sourceforge.net/projects/hhexen/

**Comment by sezero** [comment]
It was hhexen's fault. Closing this.

**Comment by sezero** [comment]
FWIW, the problem was the lack of `SDL_InitSubSystem(SDL_INIT_VIDEO)` call.

**Comment by icculus** [comment]
This was a good catch, thanks!
