### ISSUE TITLE
SDL_SetPalette incorrect return value?

### ISSUE THREAD

**Issue by tylerlm** [libsdl-org/sdl12-compat#294]
In SDL 1.2, SDL_SetPalette returns 1 on success ("if all colors were set as requested") or 0 otherwise: [SDL_video.c](https://github.com/libsdl-org/SDL-1.2/blob/52c714024e2d5a5383f64f9b119ea96cb46f9af2/src/video/SDL_video.c#L1273)

In sdl12-compat, SDL_SetPalette returns 0 on success, or -1 or SDL20_OutOfMemory() on failure: [SDL12_compat.c](https://github.com/libsdl-org/sdl12-compat/blob/c1eb2fecf9c5fc05e2efce0e2a135cd7474a4874/src/SDL12_compat.c#L7297)

(Other issues that mention the call are #216 and #283, though I'm not sure they're related)

**Comment by tylerlm** [comment]
Thanks! 

I think the no-ops on lines [7306,7310,7315](https://github.com/libsdl-org/sdl12-compat/blob/4d888293679a3e3652a11f864b8a52c9040910d0/src/SDL12_compat.c#L7306) should also be 1.

**Comment by tylerlm** [comment]
Oops, you're correct, my mistake!

@icculus, @slouken thank you for catching that, sorry for the breakage!

**Comment by tylerlm** [comment]
Ahem, my merge needs to be reverted

**Comment by icculus** [comment]
> I thought "surely these three integers will be trivial enough for a baby PR, what could go wrong". Ah well.

No worries, thank you for taking interest in the tiny details!
