### ISSUE TITLE
missing symbols left:

### ISSUE THREAD

**Issue by sezero** [libsdl-org/sdl12-compat#31]
After the #30 and #8 patches are in, these are only three SDL-1.2
symbols missing in sdl12-compat: `SDL_GL_Lock`, `SDL_GL_UpdateRects`
and `SDL_GL_Unlock`.

I don't know whether they can ever be implemented.

**Comment by icculus** [comment]
I have no recollection of these functions at all.  :)

We should also delete all the `IMPLEMENT_ME` comments about missing functions at the top of SDL12_compat.c, since they're long out of date.

**Comment by icculus** [comment]
Ok, the OpenGL stuff is super-straightforward, and just calls into the GL.

@slouken This code goes back to the initial import into CVS (!), so I don't know if we wrote it originally. Was this from you, like 20+ years ago? If it wasn't from someone else, we can copy/paste it into sdl12-compat, otherwise we have to rewrite it to avoid the LGPL.

**Comment by icculus** [comment]
Looks like it was Daniel Vogel: https://discourse.libsdl.org/t/ogl-and-sdl/2775/3

**Comment by sezero** [comment]
> Ok, the OpenGL stuff is super-straightforward, and just calls into the GL.

Wouldn't that dictate that the library to depend on libGL?
With those three being discouraged calls, should we ever do it?

**Comment by slouken** [comment]
These were from some of the original Loki ports. I think Heavy Gear 2 was one of those that relied on this.

Do we care at this point?

We can certainly stub them in, and the game'll just be missing UI and we can come back to it, if we find a use case.

**Comment by icculus** [comment]
> Wouldn't that dictate that the library to depend on libGL?

Nah, we already have a SDL_GL_GetProcAddress(), we'd just use it to look up the functions we need.

Let's stub it in for now, though. I'll try to get Heavy Gear 2 running at some point, but leave it for now.

Stub functions are in with https://github.com/libsdl-org/sdl12-compat/commit/5cb990acfef2aa9e2593f44222f0489a1e41e886 

We can close this, we've got FIXMEs for several other stubs already anyhow.

**Comment by sezero** [comment]
> > Wouldn't that dictate that the library to depend on libGL?
> 
> Nah, we already have a SDL_GL_GetProcAddress(), we'd just use it to look up the functions we need.

That might work, but only if we do it without SDL_GL_LoadLibrary, i.e. relying on
whatever library being already loaded in SDL2.

**Comment by slouken** [comment]
> > > Wouldn't that dictate that the library to depend on libGL?
> > 
> > 
> > Nah, we already have a SDL_GL_GetProcAddress(), we'd just use it to look up the functions we need.
> 
> That might work, but only if we do it without SDL_GL_LoadLibrary, i.e. relying on
> whatever library being already loaded in SDL2.

Yeah, the use case here is that the application already set up OpenGL for other rendering, and is using SDL to draw an overlay on top of that.

**Comment by icculus** [comment]
To followup: as of https://github.com/libsdl-org/sdl12-compat/commit/e208bd64a0ef22eae47c464c9968963a2153f5cc we have a basic framework for loading OpenGL symbols we need internally during SDL_SetVideoMode(..., SDL_OPENGL), so we can bolt on the things we need for SDL_OPENGLBLIT or SDL_GL_UpdateRects on that.
