### ISSUE TITLE
How about opposite approach :) ?

### ISSUE THREAD

**Issue by arczi84** [libsdl-org/sdl12-compat#312]
SDL2 library using SDL1.2 functions, software only?

**Comment by icculus** [comment]
For systems that had SDL 1.2 but not SDL2? Mac OS Classic, Dreamcast, etc?

It's an interesting idea, and I bet for a lot of games you could fake it well enough with a subset of SDL2, but it's not something we're going to build ourselves. If someone builds it in their own repository, I will totally brag about them on Twitter, though.  :)

Also, even once SDL3 is the primary library, we will still accept SDL2 patches to make old systems work. It's not inconceivable that one could revive WinCE or whatever there, the same way that OS/2 made its way into SDL2.
