### ISSUE TITLE
1.2.68 release?

### ISSUE THREAD

**Issue by smcv** [libsdl-org/sdl12-compat#319]
We've had various good fixes since 1.2.64: is it time for a 1.2.66 release?

As a small step towards that, I've uploaded a git snapshot (the latest git commit as of today, from 2023-09-04) to Debian experimental, and I'll get a test-build going for the Steam Runtime. I'd prefer to ship real releases in Debian testing/unstable and the Steam Runtime, though.

**Comment by slouken** [comment]
Yes! @icculus, you want to turn the crank?

**Comment by icculus** [comment]
Prelease 1.2.66 is up now! https://github.com/libsdl-org/sdl12-compat/releases/tag/prerelease-1.2.66

This will become the 1.2.68 official release in about a week!

**Comment by smcv** [comment]
Thanks, I'll get that packaged.

**Comment by smcv** [comment]
1.2.66 is now included in the Steam Runtime provided with the Steam client beta branch, and seems to work well with Hammerfight and the demo of Steel Storm Burning Retribution. It will be updated to 1.2.68 when available.

**Comment by icculus** [comment]
I don't think anything else is coming in for this release.

@sezero, @sulix, any last things you want added? If not, I'll probably declare this final today.

**Comment by sezero** [comment]
> @sezero, @sulix, any last things you want added? 

I don't have anything

**Comment by sezero** [comment]
> > @sezero, @sulix, any last things you want added?
> 
> I don't have anything

May I though suggest, now that you are providing windows x86 and x64 binaries with releases, that you provide SDL_mixer built from SDL-1.2 branch for windows along with them? See https://github.com/libsdl-org/sdl12-compat/issues/215#issuecomment-1271439552 as to why, and see https://github.com/libsdl-org/SDL_mixer/commit/4c47f6f3eb2fe180c9acefea91cc02ae9ba20e68 (and its follow-up https://github.com/libsdl-org/SDL_mixer/commit/615882306946a840a9725eb74e8c247dc43f9518) as to how it was fixed.

**Comment by sulix** [comment]
> @sezero, @sulix, any last things you want added? If not, I'll probably declare this final today.

No — I've got nothing planned at the moment.

**Comment by sezero** [comment]
> > > @sezero, @sulix, any last things you want added?
> > 
> > 
> > I don't have anything
> 
> May I though suggest, now that you are providing windows x86 and x64 binaries with releases, that you provide SDL_mixer built from SDL-1.2 branch for windows along with them? See [#215 (comment)](https://github.com/libsdl-org/sdl12-compat/issues/215#issuecomment-1271439552) as to why, and see [libsdl-org/SDL_mixer@4c47f6f](https://github.com/libsdl-org/SDL_mixer/commit/4c47f6f3eb2fe180c9acefea91cc02ae9ba20e68) (and its follow-up [libsdl-org/SDL_mixer@6158823](https://github.com/libsdl-org/SDL_mixer/commit/615882306946a840a9725eb74e8c247dc43f9518)) as to how it was fixed.

If interested in doing that, here are SDL_mixer 1.2 windows builds from latest git 1.2 branch:

[SDL_mixer-1.2.13-win32-x86.zip](https://github.com/libsdl-org/sdl12-compat/files/12729869/SDL_mixer-1.2.13-win32-x86.zip)

[SDL_mixer-1.2.13-win32-x64.zip](https://github.com/libsdl-org/sdl12-compat/files/12729867/SDL_mixer-1.2.13-win32-x64.zip)

**Comment by icculus** [comment]
The official 1.2.68 release is now live!

https://github.com/libsdl-org/sdl12-compat/releases/tag/release-1.2.68

I'm going to assign this to @slouken to close out this issue by posting some win32 binaries, and looking at @sezero's comments about SDL_mixer.

**Comment by smcv** [comment]
1.2.68 is included in the Steam client beta since yesterday.

**Comment by slouken** [comment]
I've added win32 binaries, and @sezero's SDL_mixer binaries. We should be good to go!
