### ISSUE TITLE
Please add SDL12COMPAT_NO_QUIT_VIDEO to the README

### ISSUE THREAD

**Issue by schauveau** [libsdl-org/sdl12-compat#329]
The video editor Flowblade is suffering from a black screen problem https://github.com/jliljebl/flowblade/issues/1134 and after a bit of digging, it appears that setting **SDL12COMPAT_NO_QUIT_VIDEO** fixes the issue. 

I found **SDL12COMPAT_NO_QUIT_VIDEO** by luck while browsing the sdl12-compat source code.  It should be documented in the README. 

More precisely, Flowblade is using the "sdl" backend of the MLT Multimedia Framework  https://www.mltframework.org/ so that issue may also affect other applications based on MLT.

**Comment by sulix** [comment]
Sorry — my fault. At the time, I thought (hoped) this would only help one program, so only documented it in COMPATIBILITY.md.

PR #330 adds this to README.md as well.
