### ISSUE TITLE
Write zlib-licensed 1.2 headers...

### ISSUE THREAD

**Issue by icculus** [libsdl-org/sdl12-compat#34]
This is super not-urgent right now, but it would be nice if we have SDL 1.2 headers under the zlib license, so sdl12-compat can be used not only as a binary-compatible drop-in replacement for libSDL-1.2, but can also be used to compile 1.2 apps from source, removing the need for distros to ship real SDL 1.2 "development" packages.

I don't know what sort of effort this would take. There's a good chance we can relicense some parts of the 1.2 headers, as its likely Sam or I wrote most of it, but I'd have to sort through them all. It's also possible that it doesn't need to be super-fancy, and we just need to have some extremely basic headers with some function declarations and macros and call it a day.

**Comment by lanodan** [comment]
Hi,
I tried to get sdl12-compat with headers (licensing isn't much of an issue to me) with using sdl12 as a base but because it uses autotools for `SDL_config.h` I didn't manage to get it to work correctly without basically needing to build sdl12 and then extract this header and use hope.

**Comment by icculus** [comment]
Right now, the way I'm doing this is to install SDL2 however one likes (from source or from a pre-built package), and then installing the libsdl-1.2-dev package (which installs SDL 1.2 headers with SDL_config.h), which is enough to get testsprite.c to compile.

But yeah, SDL_config.h is built by SDL 1.2's configure script, and unlike SDL2, it probably _needs_ a correct SDL_config.h to do the right thing when compiling external apps.

This is another good reason for us to provide replacement headers.

**Comment by Conan-Kudo** [comment]
This would be super helpful for us in Fedora, as I'd like to retire SDL 1.2 and replace it with this library.

**Comment by sjnewbury** [comment]
> Hi,
> I tried to get sdl12-compat with headers (licensing isn't much of an issue to me) with using sdl12 as a base but because it uses autotools for `SDL_config.h` I didn't manage to get it to work correctly without basically needing to build sdl12 and then extract this header and use hope.

@lanodan I've modified your ebuild to use autotools to build a minimal Makefile from the to run install-hdrs, install-man, and install sdl.m4 from the tarball.  It's all properly working with multilib and have successfully built against it.  I'll make a PR to your repo if you want.  Let me know.

**Comment by lanodan** [comment]
> > Hi,
> > I tried to get sdl12-compat with headers (licensing isn't much of an issue to me) with using sdl12 as a base but because it uses autotools for `SDL_config.h` I didn't manage to get it to work correctly without basically needing to build sdl12 and then extract this header and use hope.
> 
> @lanodan I've modified your ebuild to use autotools to build a minimal Makefile from the to run install-hdrs, install-man, and install sdl.m4 from the tarball. It's all properly working with multilib and have successfully built against it. I'll make a PR to your repo if you want. Let me know.

Yeah please do via gitlab, sending a patch/repo-URL via email, sending a URL here, latter might be better so other package maintainers can look at it.

**Comment by icculus** [comment]
Latest in revision control has replacement headers.

@Conan-Kudo, I don't suppose there's a reasonably automated way to supply these headers to a Fedora system and build every package that depends on SDL 1.2 with them? It'd be neat if we can just get a big infodump of all the packages that failed to compile with the new headers (if any!) and then work down that list fixing issues. Just looking for build results, not testing of the actual packages.

**Comment by Conan-Kudo** [comment]
@icculus There is, yes. This will land before the mass rebuild, so we'll get that info pretty easily once we do that. 😉 

I can also ask releng if we can do an ordered rebuild of everything to give you feedback.

**Comment by icculus** [comment]
Feedback sooner is better than feedback later, but don't do anything that will annoy someone else on my behalf.  :)

I was thinking more like: I install Fedora in a virtual machine, install the real SDL 1.2 package, overwrite the installed files with sdl12-compat and then try to build all packages that use 1.2 from source. A real caveman approach instead of elegant build engineering.  :)

**Comment by Conan-Kudo** [comment]
I can provide a way for you to do that, sure. 😉

**Comment by Conan-Kudo** [comment]
@icculus Here's a script that will let you just iterate through them using Mock and my `sdl12-compat` package based on the latest snapshot:

```bash
#!/bin/bash

# Test building SDL 1.2 games with sdl12-compat on Fedora

if [ $(id -u) -eq 0 ]; then
   echo "Please don't run this as root!"
   exit 1
fi

source /etc/os-release

if [ "$ID" != "fedora" ]; then
   echo "Please run this on Fedora!"
   exit 1
fi

# Install mock and configure it
#sudo dnf -y install mock
#sudo usermod -a -G mock $USER

# Get a list of packages built with SDL 1.2
sdl1_games=$(sudo dnf -q --disablerepo=\* --enablerepo=fedora-source repoquery --whatrequires "SDL-devel" --qf "%{NAME}")
SAVEIFS=$IFS   # Save current IFS
IFS=$'\n'      # Change IFS to new line
sdl1_games=($sdl1_games) # split to array
IFS=$SAVEIFS   # Restore IFS

# Generate a mock config to use sdl12-compat
cat >> /tmp/fedora-${VERSION_ID}-sdl12compat-x86_64.cfg << EOF
include('/etc/mock/fedora-${VERSION_ID}-x86_64.cfg')

config_opts['dnf.conf'] += """
[copr:copr.fedorainfracloud.org:ngompa:sdl12-compat]
name=Copr repo for sdl12-compat owned by ngompa
baseurl=https://download.copr.fedorainfracloud.org/results/ngompa/sdl12-compat/fedora-\$releasever-\$basearch/
skip_if_unavailable=False
priority=50
gpgcheck=1
gpgkey=https://download.copr.fedorainfracloud.org/results/ngompa/sdl12-compat/pubkey.gpg
enabled=1
"""
EOF

# Build packages
for sdl1_game in "${sdl1_games[@]}"
do
   dnf download --source --destdir /tmp "$sdl1_game"
   mock -r /tmp/fedora-${VERSION_ID}-sdl12compat-x86_64.cfg /tmp/${sdl1_game}*.src.rpm
   rm -v /tmp/${sdl1_game}*.src.rpm
done
```
