### ISSUE TITLE
Hammerfight: mouse don't work

### ISSUE THREAD

**Issue by OlegAckbar** [libsdl-org/sdl12-compat#341]
In Hammerfight mouse don't work with either Wayland or X11 driver.

**Comment by icculus** [comment]
So this is actually an sdl12-compat thing; Hammerfight doesn't use SDL2.

And we have a workaround for this!

https://github.com/libsdl-org/sdl12-compat/blob/bec4bd04b5fdc19bc7bf6a7a417ae79978b0344a/COMPATIBILITY.md#hammerfight-linux

All the gory technical details are in #147, but the `CORE_INIT_RI=true` config file change will solve the problem.
