### ISSUE TITLE
Mac keyboard issue with function keys

### ISSUE THREAD

**Issue by icculus** [libsdl-org/sdl12-compat#35]
Noticed one thing with keys:  With SDL-1.2, I'd hit `FN`+`<funckey>` to use
the functions keys, e.g. `FN`+`F3` to load a game, `FN`+`F10` to quit the game.
With the compat-layer, `FN`+`F3` is OK, but `FN`+`F10` does something different,
I have to use `<Option>`+`F10` for it.

_Originally posted by @sezero in https://github.com/libsdl-org/sdl12-compat/issues/28#issuecomment-791443580_

**Comment by icculus** [comment]
I think this is working now; checkkeys sees Fn+F10 as an F10 keypress on this macbook:

```
Key pressed:  291-f10  modifiers: (none)
Key released:  291-f10  modifiers: (none)
```

@sezero, let me know if this is still broken for you when you get a moment.

**Comment by sezero** [comment]
Seems to be working with latest git as of this moment.
