### ISSUE TITLE
macOS needs VERSION/SOVERSION set

### ISSUE THREAD

**Issue by DominusExult** [libsdl-org/sdl12-compat#37]
I've tried testing sdl12-compat with DOSBox but just replacing the SDL 1.2x dylib is not possible because the reported compatibility version and current version (compatibility version 0.0.0, current version 0.0.0) do not match the original SDL 1.2x version linked to (compatibility version 12.0.0, current version 12.5.0).
Adding to the Apple properties in CMakeLists
```
        VERSION "12.50.0"
        SOVERSION "12.50.0"
```
worked for DOSBox and its dependencies SDL_Sound and SDL_Net.

I noticed that this is set to 
```
        VERSION "1.2.50"
        SOVERSION "0"
```
for other platforms. Is that not so important on these or is the VERSION/SOVERSION handled differently on those than on Apple, so that the set number is so different?

**Comment by sezero** [comment]
Makefile.darwin does it right, by setting min/current to 1.0.0/12.50.0

Will work on Cmake side.

**Comment by sezero** [comment]
Fixed by https://github.com/libsdl-org/sdl12-compat/commit/1cf88a18c43eacae308015c54fd3594c108b0ba8
```
$ i686-apple-darwin9-otool -L libSDL-1.2.0.dylib
libSDL-1.2.0.dylib:
	$(HOME)/sdl12-compat/b/libSDL-1.2.0.dylib (compatibility version 1.0.0, current version 12.50.0)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 1038.36.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 125.2.11)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 227.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 550.43.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 751.62.0)
```

**Comment by DominusExult** [comment]
Thanks, but unfortunately it seems the SOVERSION needs to be set as high as well. Everything that was linked against SDL 1.2 also checks the compatibility version and refuse to run when it is lower than the one they were compiled against.

The problem is that the SDL 1.2 version built via autotools will set compatibility version 12.0.0 while if you built the lib via xcode it is set to 1. Unless I made a big mistake at some point

**Comment by sezero** [comment]
You are not mistaking: It's the big dylib version mess both SDL-1.2 _and_
SDL-2.0 still have - see: https://bugzilla.libsdl.org/show_bug.cgi?id=4208
I followed Xcode to set the version numbers, because Xcode is the toolset
used to build the official SDL binaries. If you want autotools' libtool
versions, I suggest editing CMakeLists.txt unless @icculus has a different
opinion.

**Comment by DominusExult** [comment]
I see, thanks. You are right, matching the release version makes the most sense. And since using sdl12-compat will probably always be a hands on approach anyway... :)

Maybe it could be made into a CMake option (e.g. something like -DLibraryCompatibilityVersion=x.x.x and -DLibraryVersion=x.x.x) sometime. But again, your solution works for me

**Comment by DominusExult** [comment]
May I suggest changing the DYLIB_COMPAT_VERSION line  to
`set(DYLIB_COMPAT_VERSION 1.0.0 CACHE STRING "library compatibility version")`
When  `CACHE STRING "library compatibility version"` is set it allows this to be overridden without the need to edit the CMakeLists.txt.

**Comment by sezero** [comment]
> May I suggest changing the DYLIB_COMPAT_VERSION line to
> `set(DYLIB_COMPAT_VERSION 1.0.0 CACHE STRING "library compatibility version")`
> When `CACHE STRING "library compatibility version"` is set it allows this to be overridden without the need to edit the CMakeLists.txt.

Why not change both.. Is the following good?
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 6256c3a..2231d1a 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -18,8 +18,8 @@ if(APPLE)
   set(OSX_SRCS "src/SDL12_compat_objc.m")
   set_source_files_properties(${OSX_SRCS} PROPERTIES LANGUAGE C)
   # the following matches SDL-1.2 Xcode project file
-  set(DYLIB_COMPAT_VERSION 1.0.0)
-  set(DYLIB_CURRENT_VERSION 12.50.0)
+  set(DYLIB_COMPAT_VERSION 1.0.0 CACHE STRING "library compatibility version")
+  set(DYLIB_CURRENT_VERSION 12.50.0 CACHE STRING "library current version")
   include_directories("/opt/X11/include")  # hack.
 endif()
 if(WIN32)
```

**Comment by DominusExult** [comment]
that looks good, and yes, making both changeable is better. I was a bit shortsighted, only looking at the compatibility version :)
Thanks

**Comment by sezero** [comment]
Patch applied as commit ba4c1749d2e846f
