### ISSUE TITLE
macOS: Fullscreen not working like SDL2 on multi monitor setup

### ISSUE THREAD

**Issue by DominusExult** [libsdl-org/sdl12-compat#38]
On macOS (if that makes a difference in this case) with a multi monitor setup going fullscreen with SDL2 only uses the monitor the SDL2 app is currently active. The only screen change is on the one the app is active on. All other monitors can still be used, the SDL2 app stays visible while other apps are acitve.

With SDL 1.2x the app goes fullscreen on the main screen and all others go black, no matter on which monitor the active SDL app was.

With sdl12-compat it behaves strangely:
- if you go fullscreen on the main screen (center screen), the other screens go black as with SDL 1.2x
- if you go fullscreen on another screen, all screens go black for a moment, the SDL app will be fullscreen on the monitor it was active on, the other monitors are useable. BUT if you use an app on the other monitors the SDL app will go black until you switch to it.

Tested with DOSBox SVN (there is also a patch for DOSBox to use SDL2 and with that fullscreen behaves like it should with SDL2).

**Comment by DominusExult** [comment]
Wildly replacing` SDL_WINDOW_FULLSCREEN` with `SDL_WINDOW_FULLSCREEN_DESKTOP` fixed the behavior but resulted in a weird fullscreen picture, similar to https://github.com/libsdl-org/SDL-1.2/issues/839 but this time only in fullscreen and the rendered area seems to be in the lower left quarter of the fullscreen window.

**Comment by DominusExult** [comment]
actually I just needed to enable use_gl_scaling and both the toggle and the correct rendering worked.

So maybe that FIXME needs fixing so this can be used without sorting through the code to find the environment setting :)
```
/* !!! FIXME: the reason we have a toggle to prevent this is because an app might use
           FBOs directly, and will cause this to break if they bind Framebuffer 0 instead
           of our render target. If we can fool them into calling a fake glBindFramebuffer
           that binds our logical FBO instead of the window framebuffer, we can probably
           work with these apps, too. That's easy from SDL_GL_GetProcAddress, but we
           maybe need to export the symbol from here too, for those that link against
           OpenGL directly. UT2004 is known to use FBOs with SDL 1.2, and I assume
           idTech 4 games (Doom 3, Quake 4, Prey) do as well.*/
```

**Comment by icculus** [comment]
We have GL scaling enabled by default now, which I take to mean we can close this issue? Please reopen if there's other work to be done here!

**Comment by DominusExult** [comment]
This works much better now. Thank you.
