### ISSUE TITLE
macOS: building testsprite fails

### ISSUE THREAD

**Issue by DominusExult** [libsdl-org/sdl12-compat#39]
after running cmake I get this compile error for testsprite (the lib builds correctly):
```
[100%] Linking C executable testsprite
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
     (maybe you meant: _SDL_main)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [testsprite] Error 1
make[1]: *** [CMakeFiles/testsprite.dir/all] Error 2
make: *** [all] Error 2
```

macOS 11.2.2 using SDK 10.15

**Comment by sezero** [comment]
Ugh.. It probably needs linking to SDLMain.m too.

**Comment by sezero** [comment]
I don't know whether it's worth fixing.  Me, I always do `make SDL` after cmake to build the library only.

**Comment by DominusExult** [comment]
Maybe make testsprite an extra option and only build the library on `make`

**Comment by sezero** [comment]
> Maybe make testsprite an extra option and only build the library on `make`

That makes sense.  Will try later (or, if you have a patch send it here.)

**Comment by sezero** [comment]
Applied https://github.com/libsdl-org/sdl12-compat/commit/a719acd09903a3917340f93ce223a28961d27652

Closing.
