### ISSUE TITLE
macOS: Possible to link against the SDL2 framework or library instead of hardcoding the locations?

### ISSUE THREAD

**Issue by DominusExult** [libsdl-org/sdl12-compat#40]
if sdl12-compat were linked against the SDL2 framework or dylib it would be much easier to manipulate the compat library with install_name_tool to point at the dynamic library in a bundle or a framework.

Right now it is semi hard coded. findSDL2 in the CMake finds my SDL2 dylib but once i start an app with the sdl12-compat replacement it only looks for the dynamic library in /usr/local/lib (and possibly the framework paths you coded in).

Another way to handle this could be to add a search for @loader_path/SDL20_LIBNAME (and maybe something like @loader_path/Frameworks/DL20_FRAMEWORK <- but that is probably too specific for the many ways people are bundling things) which should take care of all bundles that have all the libs in one folder.

**Comment by DominusExult** [comment]
Attached patch adds @loader_path to the bottom of the dlopen searches on macOS.
[loader_path.diff.txt](https://github.com/libsdl-org/sdl12-compat/files/6134858/loader_path.diff.txt)

**Comment by icculus** [comment]
Huh, I had no idea you could dlopen "@loader_path" like that. I assumed that was dyld magic outside of libSystem.
