### ISSUE TITLE
Linux: Unreal Tournament 2004 mouse error

### ISSUE THREAD

**Issue by TheEpicNoobZilla** [libsdl-org/sdl12-compat#50]
I've tried this to Play UT 04, but the mouse is not registered correctly. I mean the game is not registering mouse moving or blocking in the middle of the screen. I use 1280x1024 monitor.

PC specs:

OS: Ubuntu 20.04 LTS
CPU: Core 2 Duo E7200
GPU: GT 8500 512 MB
RAM: 8 GB DDR2.

The game have no such issues with SDL CL.

https://github.com/MrAlert/sdlcl

**Comment by icculus** [comment]
I’ll take a look!

**Comment by icculus** [comment]
If you hit CTRL-G to toggle mousegrab, it works; it looks like maybe it was supposed to grab the mouse on startup, but failed to?

**Comment by icculus** [comment]
Okay, better fix is in: obviously SDL 1.2 wanted to grab the mouse input for fullscreen modes, but I didn't realize it treated this like a standard SDL_WM_GrabInput(SDL_GRAB_ON) call, more or less.

This has been corrected, and it specifically solves the problem in UT2004.
