### ISSUE TITLE
GBM+GLES?

### ISSUE THREAD

**Issue by mrfixit2001** [libsdl-org/sdl12-compat#52]
Last I tested this on my Rockchip RK3328 using an application compiled for GBM and GLES2. I dropped this in place of the SDL1.2 library, the application crashed as it was initializing it's graphics stack. It was months ago so wanted to check if this was a known issue and has since been resolved or if I should plan to get logs for a future issue report. Thanks in advance!

**Comment by icculus** [comment]
Logs would be super helpful!

I would also start by running an SDL2 app just to make sure it works on the hardware, as sdl12-compat will rely on SDL2 working correctly. Sometimes things can be dicey on embedded hardware situations.

**Comment by icculus** [comment]
Gonna close this for now; if new information pops up, please feel free to reopen!

**Comment by mrfixit2001** [comment]
I went to build the head commit, but it seems it requires opengl now by default.

CMake Error at /usr/local/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY OPENGL_INCLUDE_DIR
  OpenGL)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.17/Modules/FindOpenGL.cmake:427 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:147 (find_package)

**Comment by mrfixit2001** [comment]
I can get passed opengl by disabling the tests, but then the build fails with:

SDL12_compat.c:3697:27: error: ‘SDL_PIXELFORMAT_XRGB8888’ undeclared (first use in this function); did you mean ‘SDL_PIXELFORMAT_ARGB8888’?
 3697 |         case 32: appfmt = SDL_PIXELFORMAT_XRGB8888; FIXME("bgr instead of rgb?"); break

**Comment by mrfixit2001** [comment]
If I patch to use SDL_PIXELFORMAT_ARGB8888 instead, I can get it compiled... but, when building against it it looks like your SDL_syswm header file is demanding that X11 is used, but I'm not using X11 at all.

SDL_syswm.h:65:17: fatal error: X11/Xlib.h: No such file or directory
   65 | #       include <X11/Xlib.h>

Maybe it can check for the same SDL2 variable EGL_NO_X11?

**Comment by mrfixit2001** [comment]
The good news is that if I patch out the X11 stuff then my application does appear to be running now :)

**Comment by shantigilbert** [comment]
> The good news is that if I patch out the X11 stuff then my application does appear to be running now :)

Care to share your patches? I am having the same issue compiling

**Comment by icculus** [comment]
There's like 17 legit issues reported here now, so I'm reopening so we fix them.  :)

The requirement to have OpenGL support should already be fixed; SDL 1.2 didn't really have a concept of GLES, but the only part of _building_ that cares about it is a desktop OpenGL test app which can be entirely ignored.

Other issues are still pending or haven't been started. There was a reason we needed XRGB (OpenGL logical scaling, I believe) but I didn't know it was a 2.0.14 thing; will check.

**Comment by sezero** [comment]
> Other issues are still pending or haven't been started. There was a reason we needed XRGB (OpenGL logical scaling, I believe) but I didn't know it was a 2.0.14 thing; will check.

SDL_pixels.h from SDL2 >= 2.0.14 has:
```
    SDL_PIXELFORMAT_XRGB8888 =
        SDL_DEFINE_PIXELFORMAT(SDL_PIXELTYPE_PACKED32, SDL_PACKEDORDER_XRGB,
                               SDL_PACKEDLAYOUT_8888, 24, 4),
    SDL_PIXELFORMAT_RGB888 = SDL_PIXELFORMAT_XRGB8888,
```

So, replacing `SDL_PIXELFORMAT_XRGB8888` with `SDL_PIXELFORMAT_RGB888` fixes build:
```
diff --git a/src/SDL12_compat.c b/src/SDL12_compat.c
index c36de9d..3fcea1e 100644
--- a/src/SDL12_compat.c
+++ b/src/SDL12_compat.c
@@ -3944,7 +3944,7 @@ SDL_SetVideoMode(int width, int height, int bpp, Uint32 flags12)
         case  8: appfmt = SDL_PIXELFORMAT_INDEX8; break;
         case 16: appfmt = SDL_PIXELFORMAT_RGB565; FIXME("bgr instead of rgb?"); break;
         case 24: appfmt = SDL_PIXELFORMAT_RGB24; FIXME("bgr instead of rgb?"); break;
-        case 32: appfmt = SDL_PIXELFORMAT_XRGB8888; FIXME("bgr instead of rgb?"); break;
+        case 32: appfmt = SDL_PIXELFORMAT_RGB888; FIXME("bgr instead of rgb?"); break;
         default: SDL20_SetError("Unsupported bits-per-pixel"); return NULL;
     }
 
```
E.g. I can build against SDL2-2.0.9.  OK to apply?

**Comment by sezero** [comment]
> > Other issues are still pending or haven't been started. There was a reason we needed XRGB (OpenGL logical scaling, I believe) but I didn't know it was a 2.0.14 thing; will check.
> 
> SDL_pixels.h from SDL2 >= 2.0.14 has:
> 
> ```
>     SDL_PIXELFORMAT_XRGB8888 =
>         SDL_DEFINE_PIXELFORMAT(SDL_PIXELTYPE_PACKED32, SDL_PACKEDORDER_XRGB,
>                                SDL_PACKEDLAYOUT_8888, 24, 4),
>     SDL_PIXELFORMAT_RGB888 = SDL_PIXELFORMAT_XRGB8888,
> ```

OK, went ahead and applied https://github.com/libsdl-org/sdl12-compat/commit/c5bd71de527b981ec736dbd94e973cc11de0cbc0 for this.

**Comment by mrfixit2001** [comment]
Confirmed using SDL_PIXELFORMAT_RGB888 works

**Comment by sezero** [comment]
The only issue left here is the dependence on a few X11 headers, yes?

**Comment by mrfixit2001** [comment]
I believe so, yes

**Comment by icculus** [comment]
I'm going to fight with the x11 issue.

**Comment by mrfixit2001** [comment]
For what it's worth - I just removed the entire X11 section from the header file and I've been able to use sdlcompat for all my GBM+GLES stuff. Definitely not the "right" way to fix it, but it "works" ;)

**Comment by sezero** [comment]
We can over-achieve and package the only needed 3 X11 headers under include/SDL/X11
(IIRC, they are MIT-licensed.) How bad an idea would that be?

**Comment by mrfixit2001** [comment]
Having the header files include the X11 headers for systems which don't use X11 or have the X11 libraries? 
Something about that... raises a red alert haha

My suggestion would be to update the cmake to search for the X11 libraries first and set a variable at compile time to include the headers them only if the libraries were found.

**Comment by icculus** [comment]
> How bad an idea would that be?

I think we only need these headers for Display, Window, and XEvent. I'd be more inclined to just fill those in and avoid the headers, but this might be naive of me. I'll look at it shortly.

**Comment by icculus** [comment]
> this might be naive of me

It's naive of me.

I'm wedging in something with __has_include and calling it Good Enough.

**Comment by icculus** [comment]
__has_include magic is in 4ad7ba6348d08d75496362efab1cbf099a6de42d ... I'm sort of inclined to dump X11 syswm support entirely, though, refer to comments in that commit.

But for now, this should unblock this issue, so I'm closing it.
