### ISSUE TITLE
bad revcpy implementation

### ISSUE THREAD

**Issue by Jan200101** [libsdl-org/sdl12-compat#56]
pointed out by kkofler https://github.com/libsdl-org/sdl12-compat/commit/4c5e3b22593c4b48ac8129ae2096af5c00569dd4#commitcomment-50963635

> This implementation is incorrect. The point of SDL_revcpy (reverse copy) is to copy from the end to the start rather than from the start to the end as SDL_memcpy does, which matters in case the buffers are overlapping. Compare:
> https://github.com/libsdl-org/SDL-1.2/blob/b8aa08c87e3f6e87bf918e1f2e26ebabe5f07122/src/stdlib/SDL_string.c#L320
> vs.
> https://github.com/libsdl-org/SDL-1.2/blob/b8aa08c87e3f6e87bf918e1f2e26ebabe5f07122/src/stdlib/SDL_string.c#L276
> 
> See also the difference between memcpy and memmove in the standard C library (except that memmove automatically detects the copy direction to use whereas SDL_revcpy requires you to manually choose between SDL_memcpy and SDL_revcpy). So you either have to copy the implementation of SDL_revcpy here or call SDL_memmove, not SDL_memcpy.

> Note that this bug will lead to corruption of the memory area being moved, so it needs urgent fixing.

> (Note that SDL_memmove is also subtly different in that it does not always reverse-copy, but auto-detects the safe direction to use. I am not sure whether that can be an issue in practice. But calling SDL_memcpy always does the wrong thing if SDL_revcpy is expected and will definitely break when used instead of SDL_revcpy on overlapping buffers.)

**Comment by sezero** [comment]
We can copy the implementatino from SDL-1.2, provided that re-licensing is not an issue.

**Comment by sezero** [comment]
> We can copy the implementatino from SDL-1.2, provided that re-licensing is not an issue.

As far as I can see, SDL_revcpy was by @slouken: If he or @icculus doesn't object,
we can apply the following patch (based on SDL-1.2-git):
```diff
diff --git a/src/SDL12_compat.c b/src/SDL12_compat.c
index 3a49a11..4af2595 100644
--- a/src/SDL12_compat.c
+++ b/src/SDL12_compat.c
@@ -1120,15 +1120,48 @@ SDL_snprintf(char *text, size_t maxlen, const char *fmt, ...)
     return retval;
 }
 
+#if defined(__GNUC__) && defined(__i386__)
 DECLSPEC void * SDLCALL
 SDL_revcpy(void *dst, const void *src, size_t len)
 {
-    /* this doesn't reverse the data...I think this was just a memcpy that
-       was meant to be CPU-cache friendly if you knew you were working with
-       data going backwards in memory, instead of jumping over pages to copy
-       from the start...? Whatever, just do a memcpy here. */
-    return SDL20_memcpy(dst, src, len);
+    int u0, u1, u2;
+    char *dstp = SDL_static_cast(char *, dst);
+    char *srcp = SDL_static_cast(char *, src);
+    int n = (len);
+    if (n >= 4) {
+        __asm__ __volatile__ (
+            "std\n\t"
+            "rep ; movsl\n\t"
+            "cld\n\t"
+            : "=&c" (u0), "=&D" (u1), "=&S" (u2)
+            : "0" (n >> 2),
+              "1" (dstp+(n-4)), "2" (srcp+(n-4))
+            : "memory" );
+    }
+    switch (n & 3) {
+    case 3: dstp[2] = srcp[2];
+    case 2: dstp[1] = srcp[1];
+    case 1: dstp[0] = srcp[0];
+        break;
+    default:
+        break;
+    }
+    return dst;
 }
+#else
+DECLSPEC void * SDLCALL
+SDL_revcpy(void *dst, const void *src, size_t len)
+{
+    char *srcp = (char *)src;
+    char *dstp = (char *)dst;
+    srcp += len-1;
+    dstp += len-1;
+    while ( len-- ) {
+        *dstp-- = *srcp--;
+    }
+    return dst;
+}
+#endif
 
 
 /* SDL2 doesn't have MMXExt / 3dNowExt. */
```

**Comment by sezero** [comment]
Closing after https://github.com/libsdl-org/sdl12-compat/commit/dacb4cf935ba3a6faee53c67d8973e2b375a3fe9

**Comment by icculus** [comment]
I wrote a simple implementation just in case the existing code was pasted in from another LGPL project originally, which would have been okay in LGPL SDL 1.2. Better safe than sorry.
