### ISSUE TITLE
icebreaker issues...

### ISSUE THREAD

**Issue by icculus** [libsdl-org/sdl12-compat#68]
icebreaker can be found at https://github.com/mattdm/icebreaker or just `sudo apt-get install icebreaker` on Ubuntu.

icebreaker's menu, at the top of the screen, should look like this...

![2021-05-28_19-02](https://user-images.githubusercontent.com/673562/120049228-520f0a00-bfe7-11eb-90a1-2d6a42216094.png)

Instead it looks like this (flickering lines that occasionally correct themselves)...

![2021-05-28_19-03](https://user-images.githubusercontent.com/673562/120049271-72d75f80-bfe7-11eb-85ef-b846eb550aa0.png)

It also crashes if you click the "menu" button in the bottom right during gameplay and mouse over the popped-up menu.

```
(gdb) bt
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:306
#1  0x00007ffff7622bc4 in SDL_memcpy_REAL (dst=0x0, src=0x7ffff7fc82a0 <EventQueuePool+160>, len=24) at /home/icculus/projects/SDL/src/stdlib/SDL_string.c:321
#2  0x00007ffff75aaebd in SDL_memcpy (a=0x0, b=0x7ffff7fc82a0 <EventQueuePool+160>, c=24) at /home/icculus/projects/SDL/src/dynapi/SDL_dynapi_procs.h:418
#3  0x00007ffff7fb5cdf in SDL_PollEvent (event12=0x0) at ../src/SDL12_compat.c:1739
#4  0x00007ffff7fb6001 in SDL_WaitEvent (event12=0x0) at ../src/SDL12_compat.c:1831
#5  0x000055555555d0aa in ?? ()
#6  0x000055555555e19a in ?? ()
#7  0x0000555555558ecd in ?? ()
#8  0x0000555555556a37 in main ()
```

**Comment by sezero** [comment]
SDL_WaitEvent getting a NULL param: some memory corruption somewhere?
(AFAICS, SDL-1.2 doesn't check NULL param in SDL_WaitEvent or SDL_PeepEvents
or in other procs called by it.)

**Comment by icculus** [comment]
> (AFAICS, SDL-1.2 doesn't check NULL param in SDL_WaitEvent or SDL_PeepEvents
or in other procs called by it.)

It does, deep down in SDL_PeepEvents.

You can pass a NULL to any of these functions to see if there's an event available without removing it from the event queue. Easy fix. Still have to look at the high score rendering for this bug, though.

**Comment by mattdm** [comment]
Thank you for working around my terrible code. :)
