### ISSUE TITLE
Binaries built against sdl12-compat headers don't run against real SDL 1.2 (stdinc)

### ISSUE THREAD

**Issue by sulix** [libsdl-org/sdl12-compat#73]
Not sure if this is a use case worth supporting, but:

SDL 1.2's headers define [various standard-library-esque functions](https://github.com/libsdl-org/SDL-1.2/blob/main/include/SDL_stdinc.h) like ``SDL_malloc``, ``SDL_strlen``, ``SDL_memset``, ``SDL_getenv``, etc. However, while sdl12-compat defines these in the headers unconditionally (and includes the functions in the library), the real SDL 1.2 only provides its own implementations if they're not available on the host system, and simply #defines them to the normal (non ``SDL_``) functions in the headers.

This can be reproduced by building ``testiconv`` against the sdl12-compat headers, and then running it against the ``libSDL-1.2.so.0`` included on most Linux systems (I've tried Ubuntu 21.04 and OpenSUSE Tumbleweed 20210524). It'll crash on startup with:
```
./testiconv: symbol lookup error: ./testiconv: undefined symbol: SDL_strlen
```

When built against the real SDL 1.2 headers, this works because ``SDL_strlen()`` is defined to ``strlen()``, as ``HAVE_STRLEN`` is set. When run against sdl12-compat, a real ``SDL_strlen()`` function is provided.

Personally, I think it's a good idea for sdl12-compat to include these symbols in its library unconditionally, but maybe the headers should either #define them to the equivalent stdlib functions, or (if one's really brave) change SDL-1.2 to always include and export such functions from it's library.

**Comment by icculus** [comment]
The goal with the replacement headers is to make something that will run with sdl12-compat. It's not meant to build something that will function when run with SDL 1.2 (which, depending on the luck of your configure script, very well might have provided a real SDL_strlen function).

I'm not against making things friendlier here, but the reason it currently works like this is more consistency, and more importantly, the headers don't need a custom-generated SDL_config.h. It's still not clear to me we'll completely avoid this need, but I would _really_ like to.

(in SDL2, we removed the macros that define these to be direct calls to the C runtime for this same reason, even if the implementation inside SDL2 just uses the C runtime internally to provide the functions. If we were ever doing another 1.2 release, I would do the same there. But we're not, and there's 20+ years of SDL 1.2 builds with these macros anyhow.)

**Comment by icculus** [comment]
Maybe we should wrap this in an "ifdef __linux__" (and other popular OSes where there is little doubt the C runtime is reasonable) and use the C runtime macros there.

It wouldn't be _perfect_ (I'm not installing Solaris to make sure it has snprintf), but it would cover the big cases.

You could probably just do "ifndef _MSC_VER" and cover most things correctly and wait for obscure platforms to report bugs. But it might be the only scenario we care about is Linux  (not even generically Unix) here.

sdl12-compat provides the symbols in any case.

**Comment by icculus** [comment]
I took a shot at this. It's imperfect, but it might be Good Enough for our use cases for now. If something looks like it needs tweaking, it probably does; send patches.
