### ISSUE TITLE
cmake error with mingw

### ISSUE THREAD

**Issue by sezero** [libsdl-org/sdl12-compat#85]
```
$ cmake -DSDL2_INCLUDE_DIR=/opt/SDL2/include/SDL2 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=Toolchain-MinGW64.cmake ..
-- The C compiler identification is GNU 4.5.4
-- Check for working C compiler: /opt/cross_win64/bin/x86_64-w64-mingw32-gcc
-- Check for working C compiler: /opt/cross_win64/bin/x86_64-w64-mingw32-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Could NOT find SDL2 (missing: SDL2_LIBRARY) (found version "2.0.15")
CMake Error at CMakeLists.txt:158 (install):
  install Library TARGETS given no DESTINATION!
```

This is with cmake-3.9.6.

**Comment by sezero** [comment]
This is annoying, preventing build using cmake. (Thank god I had added those standalone makefiles..)

**Comment by icculus** [comment]
My guess is that the line `include(GNUInstallDirs)` doesn't work correctly on mingw, leaving `CMAKE_INSTALL_LIBDIR` undefined, so...

```c
install(TARGETS SDL
  LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
)
```

...causes an empty string to be specified for the install location.

**Comment by Conan-Kudo** [comment]
You need a toolchain file that defines a prefix for it to work...

**Comment by sezero** [comment]
This is my toolchain file, what else am I supposed to do in it?
```
# toolchain file I use to cross compile on Linux
# targetting Windows (x64/mingw-w64). running:
# cmake -DCMAKE_TOOLCHAIN_FILE=/path/to/Toolchain-MinGW64.cmake ....

SET(CMAKE_SYSTEM_NAME Windows)

SET(CMAKE_C_COMPILER /opt/cross_win64/bin/x86_64-w64-mingw32-gcc)
SET(CMAKE_CXX_COMPILER /opt/cross_win64/bin/x86_64-w64-mingw32-g++)
SET(CMAKE_RC_COMPILER /opt/cross_win64/bin/x86_64-w64-mingw32-windres)

# where is the target environment
SET(CMAKE_FIND_ROOT_PATH /opt/cross_win64 /opt/cross_win64/x86_64-w64-mingw32)

# adjust the default behaviour of the FIND_XXX() commands:
# search headers and libraries in the target environment, search
# programs in the host environment
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
```

**Comment by Conan-Kudo** [comment]
> -- Could NOT find SDL2 (missing: SDL2_LIBRARY) (found version "2.0.15")

This seems like a separate problem...

**Comment by icculus** [comment]
> `-- Could NOT find SDL2 (missing: SDL2_LIBRARY) (found version "2.0.15")`

This, fwiw, won't stop sdl12-compat from building, because it only cares about seeing SDL2 _headers_. This line can be ignored (you can see it in successful CI builds, too).

**Comment by icculus** [comment]
> Looks like -Wall -Werror=declaration-after-statement is added not only to CFLAGS but to RCFLAGS, as well.

See if the latest in revision control fixes this, when you get a chance.

**Comment by sezero** [comment]
> > Looks like -Wall -Werror=declaration-after-statement is added not only to CFLAGS but to RCFLAGS, as well.
> 
> See if the latest in revision control fixes this, when you get a chance.

https://github.com/libsdl-org/sdl12-compat/commit/a2de2d6466928ffb813231d286b4b75e75322307 removes the -Wxxx stuff from RC_FLAGS but also from C_FLAGS.

**Comment by sezero** [comment]
> > So when I try this, I get a _different_ error:
> 
> Looks like `-Wall -Werror=declaration-after-statement` is added not only to CFLAGS but to RCFLAGS, as well.

Pushed https://github.com/libsdl-org/sdl12-compat/commit/0a951c0d094990accf4921f20e7f76b5b3dc2cb9 for this, hopefully fixing the RC_FLAGS issue and still keeping warning flags in CFLAGS.

**Comment by Conan-Kudo** [comment]
It gets further, but now I have this:

```
[  4%] Linking C shared library SDL.dll
/usr/bin/cmake -E cmake_link_script CMakeFiles/SDL.dir/link.txt --verbose=1
/usr/bin/cmake -E rm -f CMakeFiles/SDL.dir/objects.a
/usr/bin/i686-w64-mingw32-ar cr CMakeFiles/SDL.dir/objects.a @CMakeFiles/SDL.dir/objects1.rsp
/usr/bin/i686-w64-mingw32-gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions --param=ssp-buffer-size=4 -Wall -Werror=declaration-after-statement -nostdlib -fstack-protector -lssp -shared -o SDL.dll -Wl,--out-implib,libSDL.dll.a -Wl,--major-image-version,1,--minor-image-version,2 -Wl,--whole-archive CMakeFiles/SDL.dir/objects.a -Wl,--no-whole-archive @CMakeFiles/SDL.dir/linklibs.rsp
make[2]: Leaving directory '/builddir/build/BUILD/sdl12-compat-d223c862d80f0a757e5bc28a3a0eaf2f183395c2/build_win32'
/usr/lib/gcc/i686-w64-mingw32/10.3.1/../../../../i686-w64-mingw32/bin/ld: CMakeFiles/SDL.dir/objects.a(SDL12_compat.c.obj): in function `drmp3_calculate_seek_points':
/builddir/build/BUILD/sdl12-compat-d223c862d80f0a757e5bc28a3a0eaf2f183395c2/src/dr_mp3.h:4055: undefined reference to `__udivdi3'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/SDL.dir/build.make:110: SDL.dll] Error 1
make[1]: *** [CMakeFiles/Makefile2:644: CMakeFiles/SDL.dir/all] Error 2
make: *** [Makefile:139: all] Error 2
```

**Comment by sezero** [comment]
> It gets further, but now I have this:
> ```
> [...]
> /builddir/build/BUILD/sdl12-compat-d223c862d80f0a757e5bc28a3a0eaf2f183395c2/src/dr_mp3.h:4055: undefined reference to `__udivdi3'
> ```

Of course it will - it's the result of fake-cdrom support through drmp3.
The fix is adding `-static-libgcc -lgcc` to link libs.

But none of these are helping with the original issue reported here.

**Comment by sezero** [comment]
Fixed by https://github.com/libsdl-org/sdl12-compat/commit/70907e8168cccad62f4e983dcfd0dd9a2be0321c
Also pushed two other commits for cmake.
