### ISSUE TITLE
MACOSX_RPATH unused in CMakelists.txt

### ISSUE THREAD

**Issue by DominusExult** [libsdl-org/sdl12-compat#87]
Since 40572e6 added `set(CMAKE_SKIP_RPATH TRUE)` there is no longer a need for `MACOSX_RPATH 1` in the second `if(APPLE)`.
I'm not a fan of RPATH, so I set that to 0 anyway when I built it but if that was set on purpose I thought you might want to be aware of it being unused now.

**Comment by sezero** [comment]
There is also the CMP0068 warning about macosx rpath:
```
-- Configuring done
CMake Warning (dev):
  Policy CMP0068 is not set: RPATH settings on macOS do not affect
  install_name.  Run "cmake --help-policy CMP0068" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

  For compatibility with older versions of CMake, the install_name fields for
  the following targets are still affected by RPATH settings:

   SDL

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
```
This is with cmake-3.9.6.
