### ISSUE TITLE
CMake on macOS fails with OpenGl

### ISSUE THREAD

**Issue by DominusExult** [libsdl-org/sdl12-compat#94]
1eb90cb broke CMake's OpenGL check on macOS:

```
CMake Error at /opt/local/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find OpenGL (missing: OPENGL_gl_LIBRARY OPENGL_INCLUDE_DIR
  OpenGL)
Call Stack (most recent call first):
  /opt/local/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:582 (_FPHSA_FAILURE_MESSAGE)
  /opt/local/share/cmake-3.19/Modules/FindOpenGL.cmake:421 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:147 (find_package)

```

If I revert this, CMake works again.

**Comment by lanodan** [comment]
Interesting…
if you pass `-DOpenGL_GL_PREFERENCE=GLVND` to `cmake` or add `set(OpenGL_GL_PREFERENCE GLVND)` before `find_package(OpenGL` on line 147 does it works?

**Comment by DominusExult** [comment]
hmm, seems to be a problem caused by me pointing to another SDK. I'll need to investigate this further.
Let's keep this open and I'll report back if there needs something changed.
But probably I need to point at the framework somehow explicitly if I muck with SYSROOT

**Comment by DominusExult** [comment]
Entirely my problem :)
Culprit is/was that I set CMAKE_FIND_ROOT_PATH to point at my prefix and used 
```
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
```
to prevent CMake picking up things it shouldn't (for example the SDL2 framework instead of my newer git build etc...)
I'll see how to circumvent this in other ways.
*closing*
